export const chemistryA2 = {
  "23": {
    s: ["Define and use lattice energy, atomisation enthalpy, electron affinity and hydration enthalpy.", "Construct Born–Haber and enthalpy-of-solution cycles.", "Explain lattice-energy and hydration trends using ionic charge and radius.", "Use entropy and ΔG°=ΔH°−TΔS° to assess thermodynamic feasibility."],
    d: [["Lattice energy", "The enthalpy change when 1 mol of an ionic solid forms from its gaseous ions under standard conditions."], ["Atomisation enthalpy", "The enthalpy change when 1 mol of gaseous atoms forms from the element in its standard state."], ["Electron affinity", "The enthalpy change when 1 mol of gaseous atoms gains electrons to form gaseous anions."], ["Hydration enthalpy", "The enthalpy change when 1 mol of gaseous ions becomes aqueous ions under standard conditions."], ["Entropy", "A measure related to the dispersal of energy and the number of accessible arrangements."], ["Gibbs free-energy change", "ΔG, the thermodynamic quantity used to judge feasibility at a stated temperature."]],
    p: [["Born–Haber cycles", "Build the ionic solid from elements through atomisation, ionisation, electron gain and lattice formation. Hess's law makes the signed sum equal to ΔHf°. If a second electron affinity or ionisation energy is needed, include it as a separate endothermic step.", ["Write a chemical equation beside every enthalpy term.", "Use the syllabus convention: lattice formation is usually exothermic and negative."]], ["Lattice and hydration trends", "Higher ionic charge and smaller ionic radius increase electrostatic attraction, making lattice energy and hydration enthalpy more negative. Comparing experimental and theoretical lattice energies can indicate extra covalent character caused by polarisation.", ["Compare charge density, not only ionic size.", "A small highly charged cation strongly polarises a large anion."]], ["Dissolving ionic solids", "An enthalpy-of-solution cycle combines lattice dissociation with hydration of each gaseous ion. ΔHsol° alone does not determine solubility because entropy also matters, but it explains the energetic balance.", ["Reverse lattice formation when breaking the solid into gaseous ions.", "Include hydration once per mole of each ion in the formula."]], ["Entropy and Gibbs energy", "Calculate ΔS°=ΣS°products−ΣS°reactants, convert J K⁻¹ mol⁻¹ to kJ K⁻¹ mol⁻¹ when combining with ΔH, then use ΔG°=ΔH°−TΔS°. ΔG°<0 indicates thermodynamic feasibility under the stated conditions, not a fast rate.", ["Temperature must be in kelvin.", "A positive ΔG° does not prove a reaction is impossible under all non-standard conditions."]]],
    f: [["Born–Haber balance", "ΔHf°=sum of atomisation + ionisation + electron-affinity + lattice steps"], ["Solution cycle", "ΔHsol°=−ΔHlatt°+ΣΔHhyd°", "When ΔHlatt° is defined for lattice formation."], ["Entropy change", "ΔS°=ΣS°(products)−ΣS°(reactants)"], ["Gibbs equation", "ΔG°=ΔH°−TΔS°"]],
    r: [["What makes lattice energy more negative?", "Larger ionic charges and smaller ionic radii."], ["Why is the second electron affinity endothermic?", "An electron is forced onto an already negative ion, so electrostatic repulsion must be overcome."], ["What does ΔG°<0 mean?", "The process is thermodynamically feasible under the stated standard conditions; it says nothing about speed."], ["Which unit conversion is commonly missed in ΔG calculations?", "Convert ΔS from J K⁻¹ mol⁻¹ to kJ K⁻¹ mol⁻¹ if ΔH is in kJ mol⁻¹."]],
    t: ["Draw arrows in an enthalpy cycle and let their directions determine signs.", "Separate feasibility from rate in every explanation."],
    m: ["Using lattice dissociation and lattice formation signs interchangeably.", "Combining ΔH in kJ with ΔS in J.", "Claiming an exothermic reaction is automatically feasible at every temperature."],
    rel: ["5", "25", "27"]
  },
  "24": {
    s: ["Define standard electrode potential and use the standard hydrogen electrode.", "Write cell notation and calculate E°cell.", "Predict the feasible redox direction and discuss limitations of E° predictions.", "Use Q=It and F to calculate quantities in electrolysis."],
    d: [["Standard electrode potential", "The emf of a half-cell relative to the standard hydrogen electrode under standard conditions, written as a reduction."], ["Standard hydrogen electrode", "The reference half-cell with E°=0.00 V."], ["Salt bridge", "An ionic connection that completes the circuit and maintains electrical neutrality without bulk mixing."], ["Cell potential", "The potential difference between two half-cells."], ["Faraday constant", "The charge carried by 1 mol of electrons, approximately 9.65×10⁴ C mol⁻¹."], ["Electrolysis", "Using electrical energy to drive a non-spontaneous redox process."]],
    p: [["Half-cells and standard conditions", "Standard E° values refer to 298 K, solutions at 1 mol dm⁻³ and gases at 100 kPa, measured against the hydrogen electrode. Tables show reduction half-equations; a more positive E° means a greater tendency to be reduced.", ["An inert Pt electrode is needed when no conducting solid redox species is present.", "Electrons travel through the wire; ions move through the salt bridge."]], ["Cell notation and E°cell", "Write the oxidation half-cell on the left and reduction half-cell on the right, with phase boundaries | and a salt bridge ||. Calculate E°cell=E°right−E°left using reduction potentials. Balance electrons only for the overall equation; never multiply E° values by stoichiometric coefficients.", ["The cathode is reduction and the anode is oxidation.", "Include states in half-equations."]], ["Feasibility and limitations", "A positive E°cell predicts a thermodynamically feasible forward reaction under standard conditions. Actual behaviour can differ because concentrations, gas pressures and temperature are non-standard, reactions are kinetically slow, or activation energy is high.", ["Choose the oxidising agent from the more positive reduction potential.", "Do not use E° alone to predict rate."]], ["Quantitative electrolysis", "Charge Q=It. Moles of electrons equal Q/F; use the balanced electrode half-equation to convert electron moles to product moles, then to mass or gas volume. Current in amperes is coulombs per second.", ["Convert minutes to seconds.", "Use the electron coefficient from the half-equation, not the overall equation blindly."]]],
    f: [["Cell potential", "E°cell=E°cathode−E°anode"], ["Charge", "Q=It"], ["Electron amount", "n(e⁻)=Q/F"], ["Faraday constant", "F≈9.65×10⁴ C mol⁻¹"]],
    r: [["Which half-cell is on the right in standard cell notation?", "The reduction half-cell (cathode)."], ["Why are E° values not multiplied when a half-equation is scaled?", "Potential is an intensive quantity; scaling amount does not scale voltage."], ["What does positive E°cell predict?", "Thermodynamic feasibility of the written cell reaction under standard conditions."], ["How are moles of electrons found from current and time?", "Calculate Q=It, then divide by F."]],
    t: ["Write both half-equations before selecting the direction and calculating E°cell.", "State standard-condition and kinetic limitations when evaluating a prediction."],
    m: ["Adding two reduction potentials without reversing the oxidation direction conceptually.", "Multiplying E° by the electron coefficient.", "Using time in minutes in Q=It."],
    rel: ["6", "23", "28"]
  },
  "25": {
    s: ["Use Ka, pKa, Kw and pH for strong and weak acids/bases.", "Explain and calculate buffer action and buffer pH.", "Use Ksp to calculate solubility and predict precipitation.", "Use partition coefficients for solute distribution between immiscible solvents."],
    d: [["Brønsted–Lowry acid", "A proton donor."], ["Brønsted–Lowry base", "A proton acceptor."], ["Ka", "The acid-dissociation constant for HA⇌H⁺+A⁻."], ["Buffer solution", "A solution that resists pH change when small amounts of acid or alkali are added."], ["Solubility product", "Ksp, the equilibrium constant for dissolution of a sparingly soluble ionic solid."], ["Partition coefficient", "The equilibrium concentration ratio of a solute between two immiscible solvents at a fixed temperature."]],
    p: [["Acid–base equilibria", "For weak HA, Ka=[H⁺][A⁻]/[HA] and pKa=−log₁₀Ka. Set up an equilibrium table and use approximations only when justified. Kw=[H⁺][OH⁻]=1.00×10⁻¹⁴ mol² dm⁻⁶ at 298 K, so pH+pOH=14 at that temperature.", ["Strong describes extent of ionisation, not concentration.", "Check any small-x approximation against the initial concentration."]], ["Buffers", "An acidic buffer contains HA and A⁻. Added H⁺ is removed by A⁻; added OH⁻ is removed by HA. Use [H⁺]=Ka[HA]/[A⁻] or pH=pKa+log([A⁻]/[HA]), after accounting stoichiometrically for any added strong acid/base.", ["Use mole ratios when both components share the same final volume.", "Buffer capacity is finite and greatest when both components are substantial."]], ["Ksp and precipitation", "Write the dissolution equation before the Ksp expression. For MX₂⇌M²⁺+2X⁻, Ksp=[M²⁺][X⁻]²; molar solubility s gives s(2s)². After mixing solutions, calculate diluted ion concentrations and compare ionic product Qsp with Ksp.", ["Qsp>Ksp predicts precipitation.", "Stoichiometric coefficients become powers and concentration multipliers."]], ["Partition and extraction", "For solute X, Kpc=[X]organic/[X]aqueous using the stated order. Calculate amount remaining from equilibrium concentration ratios and phase volumes. Several small extractions remove more solute than one extraction with the same total solvent volume.", ["Use concentrations, not raw moles, in Kpc.", "The solute must have the same molecular form in both solvents unless the question accounts for reaction."]]],
    f: [["pH", "pH=−log₁₀[H⁺]"], ["Weak acid", "Ka=[H⁺][A⁻]/[HA]"], ["Buffer", "pH=pKa+log₁₀([A⁻]/[HA])"], ["Water", "Kw=[H⁺][OH⁻]"], ["Partition", "Kpc=[X]solvent 1/[X]solvent 2", "Use the order defined in the question."]],
    r: [["How does an acidic buffer remove added H⁺?", "Its conjugate base A⁻ reacts with H⁺ to form HA."], ["When does precipitation begin?", "When the ionic product reaches Ksp; Qsp>Ksp favours solid formation."], ["Why are several extractions more effective?", "Each fresh portion establishes a new partition equilibrium and removes a fraction of what remains."], ["What is the difference between strong and concentrated?", "Strong means nearly complete ionisation; concentrated means many moles per unit volume."]],
    t: ["Write an equilibrium equation before every constant expression.", "For buffer additions, do stoichiometric neutralisation before the equilibrium calculation."],
    m: ["Putting solids or liquid water into equilibrium expressions.", "Ignoring dilution after mixing solutions for Ksp.", "Using initial buffer amounts after strong acid/base has reacted."],
    rel: ["7", "23", "24"]
  },
  "26": {
    s: ["Determine rate equations, orders and k from data.", "Use concentration–time and initial-rate evidence, including half-life.", "Relate a rate equation to a proposed mechanism and rate-determining step.", "Use Arrhenius relationships and explain homogeneous and heterogeneous catalysis."],
    d: [["Order of reaction", "The exponent of a reactant concentration in an experimentally determined rate equation."], ["Rate constant", "k, the proportionality constant in the rate equation at a fixed temperature."], ["Half-life", "Time for a reactant concentration to fall to half its value."], ["Rate-determining step", "The slow elementary step controlling the observed rate."], ["Activation energy", "The minimum energy barrier along a reaction pathway."], ["Catalyst", "A substance that increases rate by providing a lower-activation-energy route and is regenerated overall."]],
    p: [["Rate equations from data", "For rate=k[A]ᵐ[B]ⁿ, compare experiments where one concentration changes and others stay constant. A doubled concentration causing unchanged, doubled or quadrupled rate indicates order 0, 1 or 2 respectively. Calculate k after finding all orders and derive its units from the overall order.", ["Order is experimental and need not match equation coefficients.", "Use initial rates to avoid changing concentrations during the run."]], ["Concentration–time evidence", "A zero-order graph [A] against t is linear; first-order gives constant half-life and ln[A] against t linear; second-order gives increasing half-life and 1/[A] against t linear. Gradient information can determine k where required.", ["Constant half-life is strong first-order evidence.", "Initial tangent gradients give initial rates."]], ["Mechanisms", "A proposed elementary mechanism must sum to the overall equation and reproduce the observed rate equation. Species in the slow step may determine rate; if an intermediate appears, use a preceding fast equilibrium or step relationship as directed to eliminate it.", ["A catalyst may appear in the mechanism but cancels from the overall equation.", "Reject a mechanism that conflicts with experimental orders."]], ["Temperature and catalysis", "Arrhenius gives ln k=ln A−Ea/(RT), so a plot of ln k against 1/T has gradient −Ea/R. A homogeneous catalyst shares a phase and may form intermediates; a heterogeneous catalyst adsorbs reactants, weakens bonds, allows reaction, then desorbs products.", ["Use kelvin and Ea in J mol⁻¹ with R=8.31 J K⁻¹ mol⁻¹.", "Catalysts change rate, not ΔH or equilibrium position."]]],
    f: [["Rate equation", "rate=k[A]ᵐ[B]ⁿ"], ["Overall order", "m+n+⋯"], ["Arrhenius", "k=Ae⁻ᴱᵃ⁄ᴿᵀ"], ["Linear Arrhenius", "ln k=ln A−Ea/(RT)"], ["Arrhenius gradient", "gradient of ln k vs 1/T=−Ea/R"]],
    r: [["Does stoichiometry determine reaction order?", "No; order is found experimentally unless an elementary step is explicitly considered."], ["What kinetic feature indicates first order?", "A constant half-life as concentration decreases."], ["What must a valid mechanism reproduce?", "Both the overall equation and the experimental rate equation."], ["What does a catalyst change thermodynamically?", "It changes neither ΔH nor equilibrium position; it lowers the activation barrier for both directions."]],
    t: ["Show the concentration ratio and rate ratio when deducing each order.", "Derive k units from the displayed rate equation rather than memorising."],
    m: ["Copying equation coefficients into a rate equation.", "Using Celsius in Arrhenius calculations.", "Saying a catalyst makes an equilibrium yield larger."],
    rel: ["8", "23", "28"]
  },
  "27": {
    s: ["Explain Group 2 ion and compound trends using charge density and lattice/hydration enthalpy.", "Describe solubility trends of hydroxides and sulfates.", "Explain thermal-stability trends of carbonates and nitrates.", "Apply Group 2 chemistry to qualitative and environmental contexts."],
    d: [["Charge density", "Charge per effective ionic volume; it falls down Group 2 as M²⁺ radius increases."], ["Thermal stability", "Resistance of a compound to decomposition on heating."], ["Polarisation", "Distortion of an anion's electron cloud by a cation."], ["Solubility", "The maximum equilibrium amount dissolved in a specified solvent at a stated temperature."], ["Lattice enthalpy", "The enthalpy change associated with forming an ionic lattice from gaseous ions."], ["Hydration enthalpy", "The enthalpy change when gaseous ions become hydrated aqueous ions."]],
    p: [["Ionic trends", "M²⁺ radius increases down the group while charge stays +2, so charge density and polarising power decrease. Lattice and hydration enthalpies become less negative in magnitude, but not always at the same rate.", ["Explain trends through competing enthalpy changes, not a single memorised slogan.", "The anion is constant within a solubility series."]], ["Hydroxide and sulfate solubility", "Group 2 hydroxides become more soluble down the group because lattice enthalpy weakens faster than hydration enthalpy. Sulfates become less soluble because the hydration advantage falls more significantly relative to lattice change for the large sulfate ion.", ["More soluble hydroxides give more alkaline saturated solutions.", "BaSO₄ is very insoluble and used as a sulfate test/contrast medium when appropriate."]], ["Thermal stability", "Carbonates decompose to MO+CO₂; nitrates form MO+NO₂+O₂. Stability increases down the group because larger M²⁺ ions polarise the large anions less, so their internal covalent bonds are less weakened.", ["Mg compounds decompose more readily than Ba compounds.", "Write balanced decomposition equations."]], ["Applications and observations", "Use solubility rules to predict precipitates and observations. Magnesium hydroxide can neutralise acid; calcium compounds have agricultural/building uses; barium compounds require toxicity awareness, while insoluble BaSO₄ behaves differently from soluble Ba²⁺ salts.", ["Link any use to a chemical property.", "Do not generalise toxicity without specifying the compound and solubility."]]],
    f: [["Carbonate decomposition", "MCO₃(s)→MO(s)+CO₂(g)"], ["Nitrate decomposition", "2M(NO₃)₂(s)→2MO(s)+4NO₂(g)+O₂(g)"], ["Hydroxide alkalinity", "M(OH)₂(s)⇌M²⁺(aq)+2OH⁻(aq)"]],
    r: [["Why does thermal stability increase down Group 2?", "Larger M²⁺ ions have lower charge density and polarise carbonate/nitrate ions less."], ["What is the hydroxide solubility trend?", "It generally increases down Group 2."], ["What is the sulfate solubility trend?", "It generally decreases down Group 2."], ["Why is 'lattice energy decreases' alone insufficient for solubility?", "Dissolving balances lattice breaking against hydration, so both trends must be compared."]],
    t: ["Name the specific ion and property when explaining a trend.", "Use observations such as precipitate formation only after checking the relevant solubility."],
    m: ["Giving the hydroxide trend for sulfates.", "Explaining thermal stability using bond strength in M–O only.", "Ignoring hydration enthalpy in a solubility explanation."],
    rel: ["10", "23", "25"]
  },
  "28": {
    s: ["Identify transition elements and write d-block ion electron configurations.", "Describe complexes, ligands, coordination numbers, shapes and ligand exchange.", "Explain colour and variable oxidation states, and use E° data for redox chemistry.", "Explain transition-metal catalysis and use stability constants qualitatively/quantitatively."],
    d: [["Transition element", "A d-block element forming at least one stable ion with an incomplete d subshell."], ["Ligand", "An ion or molecule donating a lone pair to a central metal ion."], ["Complex ion", "A central metal ion bonded to surrounding ligands by coordinate bonds."], ["Coordination number", "The number of coordinate bonds to the central metal ion."], ["Ligand exchange", "Replacement of one ligand in a complex by another."], ["Stability constant", "An equilibrium constant for formation of a complex from a metal ion and ligands."], ["d-orbital splitting", "Separation of d-orbital energy levels by the ligand environment."]],
    p: [["Electronic structure and oxidation states", "Remove 4s electrons before 3d when forming first-row transition-metal ions. Variable oxidation states arise because 3d and 4s energies are similar. Use oxidation numbers, charge and ligand charges to identify the metal state.", ["Zn is d-block but Zn²⁺ is d¹⁰, so it does not meet every characteristic transition definition.", "State electron configurations for the ion, not only the atom."]], ["Complexes and ligand exchange", "Common ligands include H₂O, NH₃, Cl⁻, CN⁻ and bidentate ethanedioate/ethane-1,2-diamine. Coordination 6 is usually octahedral; coordination 4 may be tetrahedral or square planar. Ligand exchange changes colour, charge and sometimes geometry.", ["Count donor atoms, not ligand molecules, for coordination number.", "Write balanced ionic equations for exchange."]], ["Colour, redox and stability", "Ligands split d orbitals; visible light promotes a d electron and the complementary colour is observed. d⁰ and d¹⁰ ions usually lack d–d colour. Use E° values to judge redox direction. Large Kstab favours complex formation; chelating ligands often gain stability partly through entropy.", ["Colour depends on metal, oxidation state, ligand and geometry.", "E° predicts feasibility, not reaction rate."]], ["Catalysis", "Homogeneous transition-metal catalysts use variable oxidation states and form intermediates, providing a lower-energy sequence. Heterogeneous metals provide adsorption sites; reactant bonds weaken, surface reaction occurs and products desorb, freeing sites.", ["A catalyst is regenerated by the end of the mechanism.", "Explain poisoning as blocking active sites where relevant."]]],
    f: [["Complex formation", "Mⁿ⁺+xL⇌[MLₓ]ⁿ⁺"], ["Stability constant", "Kstab=[MLₓ]/([M][L]ˣ)"], ["Cell feasibility", "E°cell=E°reduction−E°oxidation-side reduction potential"]],
    r: [["Which electrons are removed first from a first-row d-block atom?", "The 4s electrons are removed before 3d."], ["What does coordination number count?", "Coordinate bonds/donor atoms attached to the central ion."], ["Why are many transition-metal complexes coloured?", "Visible light is absorbed to promote electrons between ligand-split d levels."], ["Why can transition metals catalyse redox reactions?", "They access multiple oxidation states and form intermediates, creating lower-energy pathways."]],
    t: ["When naming or describing a complex, determine metal oxidation state, ligand count and overall charge separately.", "Use equations plus visible observations in ligand-exchange answers."],
    m: ["Removing 3d electrons before 4s.", "Equating number of ligand molecules with coordination number for bidentate ligands.", "Saying the catalyst changes the equilibrium constant."],
    rel: ["3", "24", "26"]
  },
  "29": {
    s: ["Use advanced organic nomenclature and recognise functional groups.", "Explain benzene bonding and aromatic delocalisation.", "Identify chiral centres, enantiomers and optical activity.", "Represent 3D stereochemistry and reason about racemic mixtures."],
    d: [["Arene", "An aromatic hydrocarbon containing a benzene ring."], ["Delocalisation", "Electron density spread over several adjacent atoms rather than confined to one bond."], ["Chiral centre", "Usually a tetrahedral carbon bonded to four different groups."], ["Enantiomers", "Non-superimposable mirror-image stereoisomers."], ["Optical activity", "Rotation of plane-polarised light by a chiral sample."], ["Racemic mixture", "An equal mixture of two enantiomers with no net optical rotation."]],
    p: [["Naming complex molecules", "Choose the parent chain/ring containing the highest-priority functional group, number for the lowest relevant locants, and name substituents alphabetically. Recognise phenyl (C₆H₅–) as a substituent and distinguish benzyl/side-chain positions when structures are supplied.", ["The suffix functional group controls the parent and numbering.", "Use commas between numbers and hyphens between numbers and words."]], ["Benzene structure", "Each carbon is trigonal planar and contributes one p orbital. Six π electrons are delocalised above and below the planar σ framework, making all C–C bonds equal and the ring more stable than a localised cyclohexa-1,3,5-triene model.", ["Use a circle or equal bonds to represent delocalisation.", "Aromatic stability helps explain substitution rather than addition."]], ["Chirality and enantiomers", "A carbon with four different substituents is chiral unless symmetry makes the whole molecule achiral. Draw mirror images with wedge/dash bonds and test superimposability. Enantiomers share most physical properties but rotate plane-polarised light equally in opposite directions and may interact differently with chiral reagents.", ["A carbon with two identical groups is not chiral.", "Do not confuse E/Z isomerism with optical isomerism."]], ["Formation and mixtures", "Attack on a planar intermediate from either face can produce equal enantiomers and a racemic mixture. A single enantiomer may form when a chiral environment, catalyst or starting material differentiates the faces. Connect stereochemical reasoning to the mechanism supplied.", ["A racemate contains molecules that are individually chiral.", "Zero net rotation results from cancellation, not absence of enantiomers."]]],
    f: [["Benzene", "C₆H₆: planar σ framework + six delocalised π electrons"], ["Optical cancellation", "equal (+) and (−) rotations ⇒ zero net rotation"]],
    r: [["What structural feature usually creates chirality?", "A tetrahedral carbon attached to four different groups."], ["Why are benzene C–C bonds equal?", "The six π electrons are delocalised around the ring."], ["Why is a racemic mixture optically inactive?", "Equal and opposite rotations from the two enantiomers cancel."], ["Are enantiomers structural isomers?", "No; they have the same connectivity and are stereoisomers."]],
    t: ["Circle every potential stereocentre and list its four substituents before deciding.", "Use the delocalised model—not alternating isolated double bonds—in explanation questions."],
    m: ["Calling any carbon with four bonds chiral.", "Saying electrons are stationary halfway between benzene bonds.", "Saying a racemate contains no optically active molecules."],
    rel: ["13", "30", "36"]
  },
  "30": {
    s: ["Describe benzene and methylbenzene reactions with reagents and conditions.", "Explain electrophilic substitution mechanisms for nitration and halogenation.", "Compare ring substitution with side-chain reactions.", "Predict directing effects of –NH₂, –OH, –R, –NO₂, –COOH and –COR."],
    d: [["Electrophile", "An electron-pair acceptor attracted to electron-rich regions."], ["Electrophilic substitution", "A reaction replacing a ring hydrogen by an electrophile while restoring aromaticity."], ["Aromatic stabilisation", "Extra stability from π-electron delocalisation around the ring."], ["Friedel–Crafts alkylation", "Ring substitution introducing an alkyl group using a halogenoalkane and AlCl₃."], ["Friedel–Crafts acylation", "Ring substitution introducing an acyl group using an acyl chloride and AlCl₃."], ["Directing group", "A substituent influencing the positions favoured by further ring substitution."]],
    p: [["Core arene reactions", "Benzene reacts with Br₂/AlBr₃ or Cl₂/AlCl₃, concentrated HNO₃/H₂SO₄ at about 25–60 °C, CH₃Cl/AlCl₃ with heat, or CH₃COCl/AlCl₃ with heat. Hydrogenation uses H₂ with Ni/Pt and heat. Learn product, reagent, catalyst and condition as one package.", ["Bromine water alone does not rapidly decolourise benzene.", "Friedel–Crafts products retain the aromatic ring."]], ["Electrophilic substitution mechanism", "Generate the electrophile (for nitration, NO₂⁺). A curly arrow moves from the benzene π system to the electrophile, producing a positively charged intermediate; a base removes H⁺ and the C–H bond electrons restore delocalisation.", ["Curly arrows begin at an electron pair or bond.", "Show the positive intermediate and restored ring."]], ["Methylbenzene and side chains", "Methylbenzene can undergo ring substitution more readily than benzene, side-chain radical halogenation under UV light, and complete side-chain oxidation with hot alkaline KMnO₄ followed by acid to benzoic acid, provided a benzylic hydrogen is present.", ["Conditions decide ring versus side-chain halogenation.", "Oxidation shortens an oxidisable alkyl side chain to –COOH."]], ["Directing effects", "–NH₂, –OH and alkyl groups direct mainly to 2/4 positions; –NO₂, –COOH and –COR direct mainly to position 3. Use the substituent already on the ring to predict major isomers without claiming a single exclusive product.", ["Number positions relative to the existing substituent.", "Directing effect and activation are related but not identical statements."]]],
    f: [["Nitrating electrophile", "HNO₃+H₂SO₄→NO₂⁺+HSO₄⁻+H₂O"], ["Side-chain oxidation", "alkylbenzene → C₆H₅COOH", "Hot alkaline KMnO₄, then dilute acid; requires a benzylic H."], ["Ring halogenation", "benzene+X₂ —AlX₃→ halogenoarene+HX"]],
    r: [["Why does benzene favour substitution over addition?", "Substitution restores aromatic delocalisation; addition would permanently lose that stabilisation."], ["What is the electrophile in nitration?", "NO₂⁺, the nitronium ion."], ["How do –OH and –NO₂ direct further substitution?", "–OH mainly directs 2/4; –NO₂ mainly directs 3."], ["What conditions favour side-chain chlorination of methylbenzene?", "Chlorine with UV light/free-radical conditions rather than AlCl₃ ring-substitution conditions."]],
    t: ["For every organic reaction, revise reagent, condition, product and mechanism type together.", "Place curly-arrow tails exactly at the bond or lone pair supplying electrons."],
    m: ["Drawing electrophilic addition instead of substitution.", "Using bromine water without a halogen carrier for benzene ring bromination.", "Ignoring reaction conditions when choosing ring versus side-chain substitution."],
    rel: ["14", "29", "31", "32"]
  },
  "31": {
    s: ["Prepare halogenoarenes by electrophilic substitution.", "Explain the reactivity difference between halogenoalkanes and halogenoarenes.", "Distinguish ring and side-chain halogenation conditions in arenes.", "Apply structure and bonding to nucleophilic-substitution predictions."],
    d: [["Halogenoarene", "A compound with halogen directly bonded to an aromatic-ring carbon."], ["Halogenoalkane", "A compound with halogen bonded to an sp³ carbon of an alkyl group."], ["Halogen carrier", "A Lewis-acid catalyst such as AlCl₃ or AlBr₃ that helps generate an electrophile."], ["Partial double-bond character", "Bond strengthening caused by overlap/delocalisation that makes a bond shorter and harder to break."], ["Nucleophile", "An electron-pair donor."], ["Hydrolysis", "Bond cleavage involving water or aqueous hydroxide." ]],
    p: [["Making halogenoarenes", "React benzene or methylbenzene with Cl₂/AlCl₃ or Br₂/AlBr₃ to substitute a ring hydrogen. With methylbenzene, the alkyl group directs mainly to 2 and 4 positions. Write HCl or HBr as the other product.", ["The catalyst is a halogen carrier, not UV light.", "State positional isomers where the directing effect matters."]], ["Halogenoarene bonding", "In chlorobenzene, a chlorine lone pair overlaps with the ring π system, giving the C–Cl bond partial double-bond character. The ring carbon is sp² and the bond is shorter/stronger than in chloroethane, so nucleophilic substitution/hydrolysis is much harder.", ["Do not explain the lower reactivity only by bond polarity.", "Delocalisation involves a chlorine lone pair and the aromatic system."]], ["Ring versus side chain", "Cl₂/AlCl₃ gives ring substitution; Cl₂ under UV radical conditions attacks an alkyl side chain. The substrate and conditions must both be read before predicting the product.", ["A halogen on the side-chain carbon is a halogenoalkane functional group.", "A halogen directly on the ring is a halogenoarene."]], ["Comparative reaction reasoning", "Halogenoalkanes can undergo nucleophilic substitution because their polar Cδ⁺–Xδ⁻ bond is accessible and breakable under suitable conditions. Halogenoarenes resist the same conditions because the aromatic carbon–halogen bond is strengthened and the planar electron-rich ring disfavors the usual pathway.", ["Compare bond strength, hybridisation/environment and mechanism.", "Use named example pairs such as chloroethane/chlorobenzene."]]],
    f: [["Ring chlorination", "C₆H₆+Cl₂ —AlCl₃→ C₆H₅Cl+HCl"], ["Ring bromination", "C₆H₆+Br₂ —AlBr₃→ C₆H₅Br+HBr"]],
    r: [["Why is chlorobenzene less reactive than chloroethane to nucleophiles?", "Its C–Cl bond has partial double-bond character from delocalisation and is shorter/stronger on an sp² carbon."], ["What conditions chlorinate the aromatic ring?", "Cl₂ with AlCl₃ as halogen carrier."], ["What conditions favour side-chain chlorination?", "Cl₂ with UV light/free-radical conditions."], ["How is a halogenoarene identified?", "The halogen is directly bonded to an aromatic-ring carbon."]],
    t: ["Draw the bond to the ring explicitly before classifying the compound.", "Use a comparison structure: feature in halogenoarene → consequence → lower reactivity."],
    m: ["Calling benzyl chloride a halogenoarene.", "Using UV light for electrophilic ring substitution.", "Explaining chlorobenzene only through a less polar C–Cl bond."],
    rel: ["15", "30", "36"]
  },
  "32": {
    s: ["Form esters from alcohols/phenols and acyl chlorides.", "Describe preparation and reactions of phenol.", "Explain acidity differences among water, phenol, alcohols and carboxylic acids.", "Explain activated ring substitution and 2,4,6 direction by –OH."],
    d: [["Phenol", "A compound with –OH directly attached to an aromatic ring."], ["Phenoxide ion", "C₆H₅O⁻, the conjugate base of phenol."], ["Acidity", "Tendency to donate H⁺; stronger acids form more stable conjugate bases."], ["Diazonium salt", "An aromatic compound containing the –N₂⁺ group, formed cold from a primary aromatic amine."], ["Azo compound", "A coloured compound containing an –N=N– link between carbon groups."], ["Acylation", "Introduction of an acyl group, often by reaction with an acyl chloride." ]],
    p: [["Alcohol acylation", "Alcohols react with acyl chlorides at room temperature to form esters and HCl. This is faster and more complete than acid-catalysed esterification. Name the ester by the alcohol-derived alkyl group followed by the acid-derived carboxylate.", ["Acyl chlorides fume in moist air because hydrolysis releases HCl.", "Keep the carbonyl oxygen in the acyl fragment."]], ["Making and reacting phenol", "Phenylamine reacts with HNO₂ generated from NaNO₂/dilute acid below 10 °C to form a diazonium salt; warming with water gives phenol. Phenol reacts with Na or NaOH to form phenoxide, with dilute HNO₃ at room temperature to give 2-/4-nitrophenol, and with Br₂(aq) to give 2,4,6-tribromophenol.", ["Cold conditions stabilise the diazonium ion.", "Bromination gives a white precipitate and decolourises bromine water."]], ["Acidity", "Phenol is more acidic than ethanol because negative charge in phenoxide is delocalised into the ring; ethoxide has no comparable stabilisation. Phenol is less acidic than carboxylic acids, whose carboxylate charge is delocalised equally over two electronegative oxygen atoms.", ["Phenol reacts with NaOH but not normally Na₂CO₃.", "Use conjugate-base stability in explanations."]], ["Activated ring and azo coupling", "The –OH group donates electron density into the ring, activating it and directing substitution to 2,4,6 positions, so phenol nitrates/brominates under milder conditions than benzene. In alkaline solution, phenoxide couples with a diazonium ion to form an azo dye.", ["Compare conditions explicitly with benzene.", "Show the –N=N– linkage in an azo product."]]],
    f: [["Acylation", "RCOCl+R′OH→RCOOR′+HCl"], ["Phenol acidity", "C₆H₅OH+OH⁻→C₆H₅O⁻+H₂O"], ["Phenol bromination", "C₆H₅OH+3Br₂→2,4,6-C₆H₂Br₃OH+3HBr"]],
    r: [["Why is phenol more acidic than ethanol?", "Phenoxide is resonance-stabilised by delocalisation into the aromatic ring; ethoxide is not."], ["How is phenol made from phenylamine?", "Diazotise below 10 °C with HNO₂, then warm the diazonium salt with water."], ["Why does phenol brominate without AlBr₃?", "–OH donates electron density and activates the ring."], ["What links the rings in an azo dye?", "An –N=N– group."]],
    t: ["Use conjugate-base structures when comparing acid strength.", "Attach conditions to phenol reactions because they distinguish them from benzene reactions."],
    m: ["Saying phenol is a typical alcohol.", "Using concentrated nitrating mixture as the only phenol nitration condition.", "Claiming phenoxide charge stays only on oxygen."],
    rel: ["16", "30", "33", "34"]
  },
  "33": {
    s: ["Prepare benzoic acid and acyl chlorides and explain carboxylic-acid acidity.", "Form esters using acyl chlorides.", "Describe acyl-chloride reactions with water, alcohols, phenol, ammonia and amines.", "Draw the addition–elimination mechanism and compare hydrolysis reactivity."],
    d: [["Acyl chloride", "A reactive carboxylic-acid derivative with functional group –COCl."], ["Nucleophilic acyl substitution", "Addition to a carbonyl followed by elimination of a leaving group."], ["Amide", "A carboxylic-acid derivative containing –CONH₂, –CONHR or –CONR₂."], ["Electron-withdrawing group", "A group that pulls electron density and can stabilise nearby negative charge."], ["Benzoic acid", "C₆H₅COOH, an aromatic carboxylic acid."], ["Ester", "A derivative containing –COOR." ]],
    p: [["Carboxylic acids", "Oxidise an alkylbenzene with a benzylic hydrogen using hot alkaline KMnO₄ then acidify to obtain benzoic acid. Convert RCOOH to RCOCl using PCl₅, PCl₃ with heat or SOCl₂. Methanoic and ethanedioic acids can be further oxidised under the syllabus reagents.", ["Write observations/products for oxidising-agent tests where asked.", "SOCl₂ gives gaseous by-products that help drive formation."]], ["Acidity trends", "Carboxylic acids are stronger than phenols and alcohols because carboxylate charge is delocalised equally over two oxygen atoms. Electron-withdrawing chlorine substituents stabilise the carboxylate by an inductive effect; more/closer Cl atoms generally increase acidity.", ["Compare conjugate bases, not the O–H bond alone.", "Inductive effect weakens with distance."]], ["Acyl-chloride reactions", "At room temperature RCOCl reacts with water→RCOOH, alcohol→ester, phenol→ester, NH₃→primary amide, and primary/secondary amines→substituted amides, releasing HCl. Extra ammonia/amine may neutralise HCl to an ammonium salt.", ["Identify the nucleophile and the group replacing Cl.", "Phenol acylation does not require the same harsh conditions as direct carboxylic-acid esterification."]], ["Addition–elimination mechanism", "A nucleophile attacks the δ⁺ carbonyl carbon and the C=O π electrons move to oxygen. The tetrahedral intermediate collapses, re-forming C=O and expelling Cl⁻; proton transfer yields the neutral product. Acyl chlorides hydrolyse far more readily than halogenoalkanes or halogenoarenes because the carbonyl activates the acyl carbon and Cl⁻ is a good leaving group.", ["Curly arrows must start at electron pairs/bonds.", "Show intermediate charge and proton transfer clearly."]]],
    f: [["Acyl chloride hydrolysis", "RCOCl+H₂O→RCOOH+HCl"], ["Ester formation", "RCOCl+R′OH→RCOOR′+HCl"], ["Primary amide", "RCOCl+2NH₃→RCONH₂+NH₄Cl"], ["Acid conversion", "RCOOH —SOCl₂/PCl₅/PCl₃→ RCOCl"]],
    r: [["Why are carboxylic acids stronger than phenols?", "The carboxylate negative charge is delocalised equally over two oxygen atoms and is more stabilised."], ["What are the two stages of acyl substitution?", "Nucleophilic addition to the carbonyl, then elimination of Cl⁻ as C=O reforms."], ["What does an acyl chloride form with a primary amine?", "An N-substituted amide, with HCl captured by excess amine where applicable."], ["Why are acyl chlorides highly reactive to water?", "The carbonyl carbon is strongly electrophilic and chloride is a good leaving group."]],
    t: ["Build reaction maps around RCOCl because one reagent connects acids, esters and amides.", "Draw every organic mechanism with charges, lone-pair origin and the leaving group."],
    m: ["Drawing nucleophilic substitution directly at the carbonyl without the tetrahedral intermediate.", "Forgetting the HCl/by-product or second ammonia equivalent.", "Explaining acid strength without comparing conjugate-base stability."],
    rel: ["18", "32", "34", "35", "36"]
  },
  "34": {
    s: ["Prepare primary/secondary amines and compare their basicity.", "Describe phenylamine reactions, diazotisation and azo coupling.", "Prepare and hydrolyse amides.", "Explain amino-acid zwitterions, acid–base behaviour and peptide links."],
    d: [["Amine", "An ammonia derivative with one or more H atoms replaced by carbon groups."], ["Phenylamine", "C₆H₅NH₂, a primary aromatic amine."], ["Diazotisation", "Conversion of a primary aromatic amine to a diazonium salt using nitrous acid below 10 °C."], ["Zwitterion", "A species carrying both positive and negative charges but no overall charge."], ["Peptide bond", "The amide link –CONH– formed between amino acids."], ["Basicity", "Tendency to accept a proton, governed by lone-pair availability." ]],
    p: [["Preparing amines", "Heat a halogenoalkane with excess ethanolic NH₃ under pressure for a primary amine; reaction with a primary amine can form a secondary amine. Reduce nitriles with LiAlH₄ or H₂/Ni, and reduce amides with LiAlH₄. Choose routes by the required carbon skeleton.", ["Nitrile reduction adds/retains the nitrile carbon in the chain.", "Excess ammonia reduces further substitution."]], ["Basicity", "Amines accept H⁺ through the N lone pair. Alkyl groups donate electron density and usually make aliphatic amines stronger bases than NH₃. Phenylamine is weaker because its lone pair is delocalised into the benzene ring and is less available for protonation.", ["Compare lone-pair availability in the conjugate pair.", "Amides are much weaker bases because the N lone pair is delocalised into C=O."]], ["Phenylamine and azo chemistry", "Phenylamine reacts with bromine water to form 2,4,6-tribromophenylamine. With NaNO₂/dilute acid below 10 °C it forms a diazonium salt, which can warm with water to phenol or couple with activated rings such as phenol in alkaline conditions to form coloured azo compounds.", ["Temperature control prevents diazonium decomposition.", "Show the azo –N=N– linkage between aromatic groups."]], ["Amides and amino acids", "Acyl chlorides react with NH₃/amines to form amides. Amides hydrolyse under acidic or alkaline conditions to carboxylic-acid/carboxylate products and ammonium/amine products. Amino acids exist as zwitterions near neutral pH, form cations in acid and anions in alkali, and condense through –COOH and –NH₂ to form peptide links.", ["Draw ionic forms with correct charges.", "Peptide hydrolysis restores amino-acid functional groups."]]],
    f: [["Primary amine salt", "RNH₂+H⁺⇌RNH₃⁺"], ["Diazotisation", "C₆H₅NH₂+HNO₂+H⁺→C₆H₅N₂⁺+2H₂O", "Below 10 °C."], ["Peptide link", "–COOH + H₂N– → –CONH– + H₂O"], ["Amide formation", "RCOCl+2NH₃→RCONH₂+NH₄Cl"]],
    r: [["Why is phenylamine weaker than an alkylamine?", "Its nitrogen lone pair is delocalised into the aromatic ring and is less available to accept H⁺."], ["Why is diazotisation kept below 10 °C?", "Aromatic diazonium salts decompose more readily when warmed."], ["What forms when an amino acid is placed in acid?", "The amine is protonated, giving an overall cationic form."], ["What functional group is a peptide bond?", "An amide link, –CONH–."]],
    t: ["Use structures, not only names, for amino-acid ionic forms and azo products.", "When selecting an amine synthesis, track every carbon atom through the route."],
    m: ["Saying the phenylamine lone pair is unavailable because nitrogen has no lone pair.", "Forgetting cold conditions for diazonium formation.", "Drawing an amino acid with incompatible protonation states for the stated pH."],
    rel: ["19", "32", "33", "35", "36"]
  },
  "35": {
    s: ["Explain addition and condensation polymerisation and identify repeat units.", "Deduce monomers from polyester and polyamide repeat units.", "Describe polymer hydrolysis and relate structure to degradability.", "Evaluate disposal, recycling and environmental impacts using chemical reasoning."],
    d: [["Addition polymerisation", "Joining unsaturated monomers without eliminating a small molecule."], ["Condensation polymerisation", "Joining bifunctional monomers while eliminating a small molecule such as H₂O or HCl."], ["Polyester", "A condensation polymer containing –COO– links."], ["Polyamide", "A condensation polymer containing –CONH– links."], ["Repeat unit", "The smallest structural section that repeats along a polymer chain."], ["Biodegradable", "Capable of breakdown by biological action under suitable conditions." ]],
    p: [["Addition versus condensation", "Addition polymers come from C=C monomers and their repeat units contain only atoms from the monomer. Condensation polymers need two functional groups per monomer; each link forms with loss of a small molecule. Name the link and show open bonds through repeat-unit brackets.", ["The repeat unit must preserve chain connectivity.", "Do not include n copies of a small-molecule by-product inside the repeat unit."]], ["Polyesters", "A diol plus a dicarboxylic acid forms –O–C(=O)– ester links with water loss; a diol plus a diacyl chloride can form the same links with HCl loss. Hydrolysis cleaves the ester link under acidic or alkaline conditions.", ["Cut the repeat unit through ester links to recover both bifunctional monomers.", "Under alkaline hydrolysis, carboxylate salts form before acidification."]], ["Polyamides and peptides", "A diamine plus a dicarboxylic acid/diacyl chloride forms –NH–C(=O)– links. Amino acids can self-condense into polypeptides. Hydrolysis breaks amide links but generally needs stronger conditions than ester hydrolysis.", ["Restore –NH₂ and –COOH at the cut bonds when deducing monomers.", "Account for protonation state under acidic/alkaline hydrolysis."]], ["Properties and sustainability", "Condensation polymers containing hydrolysable links can be more degradable than C–C addition polymers, but real biodegradation depends on crystallinity, access, temperature and enzymes. Evaluate reuse, mechanical/chemical recycling, feedstock and energy use instead of assuming one disposal route is always best.", ["Biodegradable does not mean instant breakdown everywhere.", "Link a property claim to a named structural feature."]]],
    f: [["Polyester link", "–O–C(=O)–"], ["Polyamide link", "–NH–C(=O)–"], ["Condensation pattern", "bifunctional monomers → polymer + small molecule"]],
    r: [["What feature identifies a polyester?", "Repeated ester links, –COO–, in the main chain."], ["How are monomers recovered from a polyamide repeat unit?", "Cut the C(=O)–N links and restore –COOH/acid-derivative and –NH₂ ends."], ["Why can condensation polymers be hydrolysed?", "Their ester or amide links can react with water under suitable acid/base conditions."], ["Does biodegradable mean harmless or instantly decomposed?", "No; breakdown depends on environment and products, so conditions and life-cycle effects matter."]],
    t: ["Mark the exact link before drawing monomers or hydrolysis products.", "Show two continuation bonds through every repeat-unit bracket."],
    m: ["Leaving a C=C bond in an addition-polymer repeat unit.", "Cutting the wrong bond when deducing condensation monomers.", "Calling every condensation polymer readily biodegradable."],
    rel: ["20", "33", "34", "36"]
  },
  "36": {
    s: ["Recall the complete AS+A Level organic reaction network with reagents and conditions.", "Plan efficient multi-step routes and identify required functional-group interconversions.", "Use observations, products and mechanisms to deduce unknown structures.", "Evaluate route selectivity, yield, purification and practical feasibility."],
    d: [["Synthetic route", "An ordered sequence converting a starting material into a target compound."], ["Functional-group interconversion", "Changing one functional group into another while managing the carbon skeleton."], ["Selectivity", "Preference for one reaction site or product over alternatives."], ["Protecting strategy", "Temporarily masking a reactive group when necessary; only used when supported by the chemistry given."], ["Overall yield", "The product of fractional yields for every step."], ["Retrosynthesis", "Planning backwards from the target to plausible precursors." ]],
    p: [["Build a reaction map", "Organise reactions by functional group: alkene, halogenoalkane, alcohol, carbonyl, nitrile, amine, carboxylic acid, acyl chloride, ester, amide and arene. For each arrow learn reagent, conditions, product and mechanism/observation where required.", ["Revise reversible arrows and oxidation stages explicitly.", "Track carbon-count changes in nitrile and Friedel–Crafts steps."]], ["Plan backwards", "Identify the target's key bond and functional group, then ask which immediate precursor produces it reliably. Continue backwards until reaching the given starting material, then check the route forward for compatible reagents and conditions.", ["A route is invalid if an earlier reagent also destroys another required group.", "Prefer syllabus reactions with unambiguous products."]], ["Deducing structures", "Combine molecular formula/unsaturation, chemical tests, oxidation/reduction products and spectroscopic evidence. Each observation constrains the structure: use all evidence and verify atom count, functional groups and possible isomers.", ["A negative test is evidence too.", "State why each datum supports or excludes a feature."]], ["Yield and practical choices", "Overall percentage yield equals the product of step yields as decimals×100. More steps usually lower overall yield and increase time/waste. Consider selectivity, hazardous reagents, separation of isomers, purification and whether a gaseous/by-product drives equilibrium.", ["Do not add percentage yields.", "A shorter route is not automatically better if it lacks selectivity."]], ["Mechanism-led predictions", "Use electrophile/nucleophile and bond polarity to predict unfamiliar reactions. Curly arrows show electron-pair movement, charges are conserved, and intermediates must connect reactant to product. Mechanistic consistency is a powerful structure check.", ["Start arrows at electrons.", "Account for every atom and overall charge."]]],
    f: [["Overall yield", "overall %=100×(yield₁/100)(yield₂/100)⋯"], ["Carbon-chain extension", "R–X→R–CN→R–CH₂NH₂ or R–COOH", "Use the stated reduction/hydrolysis conditions."], ["Acyl hub", "RCOOH⇄RCOCl→ester/amide"]],
    r: [["Why plan a synthesis backwards?", "The target functional group suggests reliable immediate precursors, narrowing possible routes."], ["How are step yields combined?", "Multiply their decimal yields, then convert back to a percentage."], ["What must every curly arrow show?", "Movement of an electron pair from a bond/lone pair to its destination."], ["How should several analytical clues be used?", "Intersect all constraints and then verify formula, functional groups and reactions against the proposed structure."]],
    t: ["Annotate every route arrow with reagent and condition, not just the product.", "At the end, count carbons and check no step changes the skeleton unintentionally."],
    m: ["Adding percentage yields across steps.", "Suggesting a correct conversion with missing or incompatible conditions.", "Using one positive test while ignoring contradictory evidence."],
    rel: ["29", "30", "31", "32", "33", "34", "35", "37"]
  },
  "37": {
    s: ["Interpret chromatography and calculate Rf values.", "Use ¹³C NMR to count carbon environments and identify chemical environments.", "Use ¹H NMR chemical shift, integration, splitting and D₂O exchange.", "Combine chromatographic, mass, infrared and NMR evidence to determine structures."],
    d: [["Chromatography", "Separation by different affinities for stationary and mobile phases."], ["Rf value", "Distance moved by a solute divided by distance moved by the solvent front."], ["Chemical shift", "NMR signal position δ in ppm relative to a reference."], ["Integration", "Relative area of a ¹H NMR signal, proportional to the number of equivalent protons."], ["Splitting", "Signal multiplicity caused by coupling to neighbouring non-equivalent protons."], ["Chemical environment", "The electronic surroundings that make nuclei equivalent or non-equivalent."], ["Molecular ion", "The ion corresponding approximately to the intact molecule in a mass spectrum." ]],
    p: [["Chromatography", "A component travels further when it has greater affinity for the mobile phase and weaker attraction to the stationary phase. In TLC/paper chromatography, Rf is dimensionless and only comparable under identical conditions. One spot can suggest purity but co-elution is possible.", ["Mark the solvent front immediately.", "Measure from the baseline to the centre of each spot."]], ["¹³C NMR", "The number of signals gives the number of distinct carbon environments, reduced by symmetry. Chemical-shift ranges indicate environments such as alkyl, C–O/C–X, C=C/aromatic and C=O. Routine proton-decoupled ¹³C spectra do not use peak integration to count carbons.", ["Equivalent carbons produce one signal.", "Use the syllabus data table rather than memorised exact shifts."]], ["¹H NMR", "Count proton environments, use δ for functional surroundings, integration for relative proton numbers and the n+1 rule for n equivalent neighbouring protons on adjacent atoms. OH/NH signals may be broad/variable and disappear on D₂O exchange; they may not split predictably.", ["Simplify integration ratios to whole-number proton counts.", "Apply splitting only between appropriate non-equivalent neighbouring protons."]], ["Combining evidence", "Start with molecular formula or M⁺ and degree-of-unsaturation ideas, identify functional groups from IR/tests, then construct fragments from NMR integration/splitting and join them while matching every carbon/proton environment. Chromatography can distinguish mixture components and monitor purity.", ["A final structure must explain every signal and observation.", "Predict the spectrum back from the proposed structure as a check."]]],
    f: [["Rf", "Rf=distance moved by solute/distance moved by solvent front"], ["¹H splitting", "n equivalent neighbouring H ⇒ n+1 lines", "Use only where coupling assumptions are valid."], ["Integration", "signal-area ratio ∝ equivalent-proton ratio"]],
    r: [["Why can Rf values only be compared under the same conditions?", "Solvent, stationary phase and temperature affect the partitioning and travel distance."], ["What does the number of ¹³C signals show?", "The number of distinct carbon environments, accounting for symmetry."], ["What information does ¹H integration give?", "The relative number of equivalent protons producing each signal."], ["What does a D₂O exchange peak reveal?", "An exchangeable O–H or N–H proton signal disappears."], ["How should a proposed structure be checked?", "Predict all expected NMR environments, integrations/splitting and ensure all other evidence is explained."]],
    t: ["Create an evidence table: datum → structural implication → remaining possibilities.", "Do not identify a whole molecule from one peak; combine every technique."],
    m: ["Counting ¹³C peak height as the number of carbons.", "Applying n+1 splitting across oxygen or to exchangeable OH/NH without justification.", "Accepting a structure that leaves an unexplained signal."],
    rel: ["22", "29", "36"]
  }
};
