export const mathA2 = {
  "3.1": {
    s: [
      "Solve equations and inequalities involving |ax + b| and interpret modulus graphs.",
      "Divide polynomials of degree at most 4 and use the factor and remainder theorems.",
      "Decompose proper rational functions into partial fractions, including repeated linear and irreducible quadratic factors.",
      "Expand (1 + x)ⁿ for rational n and state the interval of validity after any substitution."
    ],
    d: [["Modulus", "|x| is the non-negative distance of x from 0."], ["Remainder theorem", "The remainder when f(x) is divided by x − a is f(a)."], ["Factor theorem", "x − a is a factor of f(x) exactly when f(a) = 0."], ["Proper fraction", "A rational expression whose numerator has lower degree than its denominator."], ["Binomial series", "An expansion of (1 + x)ⁿ that is infinite when n is not a non-negative integer."]],
    p: [
      ["Modulus equations and inequalities", "Treat |u| as a distance. For b > 0, |u| = b gives u = ±b, |u| < b gives −b < u < b, and |u| > b gives u < −b or u > b. For expressions on both sides, critical points or squaring can help, but every solution must satisfy the original relation.", ["Sketch y = |ax + b| by reflecting negative y-values above the x-axis.", "Use interval notation or a number line to communicate inequality answers clearly."]],
      ["Polynomial division and theorems", "Write missing powers with zero coefficients before long division. If f(x) = (x − a)q(x) + r, then r = f(a). Use known factors to reduce a cubic or quartic, then solve the remaining factor completely.", ["For a divisor ax + b, test x = −b/a.", "Match coefficients only after expanding both sides in descending powers."]],
      ["Partial fractions", "First check that the fraction is proper. Use A/(ax+b) + B/(cx+d) for distinct linear factors, A/(ax+b) + B/(ax+b)² for a repeated factor, and (Bx+C)/(x²+d) over an irreducible quadratic. Cover-up works for simple linear factors; substitution and coefficient comparison finish the rest.", ["Polynomial division comes before decomposition when degrees are equal or numerator degree is larger.", "A quadratic denominator needs a linear numerator."]],
      ["General binomial expansion", "Use (1 + x)ⁿ = 1 + nx + n(n−1)x²/2! + n(n−1)(n−2)x³/3! + ⋯. Rewrite expressions into this form first. The series is valid for |x| < 1, so after substituting x = g(t), solve |g(t)| < 1.", ["Keep exact fractional coefficients until the final line.", "Only include the requested highest power; cross-terms can contribute to it."]]
    ],
    f: [["Modulus interval", "|x − a| < b ⇔ a − b < x < a + b", "For b > 0."], ["Remainder theorem", "f(x) = (x − a)q(x) + f(a)"], ["General binomial", "(1 + x)ⁿ = 1 + nx + n(n−1)x²/2! + ⋯", "Valid for |x| < 1 when the expansion is infinite."]],
    r: [["What partial-fraction numerator belongs above an irreducible quadratic?", "Use a linear numerator, for example (Bx + C)/(x² + d)."], ["How do you test whether x − a is a factor?", "Calculate f(a); it is a factor exactly when f(a) = 0."], ["What is the validity condition for a general binomial expansion?", "The substituted quantity playing the role of x must have modulus less than 1."], ["Why check modulus solutions?", "Squaring or splitting cases can introduce values that do not satisfy the original equation or inequality."]],
    t: ["State the range of x for every infinite binomial expansion.", "When a factor is ax + b, use its root −b/a rather than b."],
    m: ["Decomposing an improper rational expression before polynomial division.", "Putting a constant numerator above an irreducible quadratic factor.", "Forgetting that a strict modulus inequality gives strict endpoints."],
    rel: ["3.5", "3.9"]
  },
  "3.2": {
    s: ["Use laws of logarithms and the inverse relationship between eˣ and ln x.", "Solve equations and inequalities with an unknown in an exponent.", "Transform y = Axⁿ and y = Abˣ to linear form and identify constants from gradient/intercept.", "Interpret exponential growth and decay models in context."],
    d: [["Natural logarithm", "ln x is logarithm to base e and is defined only for x > 0."], ["Inverse functions", "eˣ and ln x undo one another: ln(eˣ)=x and eˡⁿˣ=x for x>0."], ["Exponential model", "A quantity whose rate or repeated proportional change is tied to its current value."], ["Linearisation", "Transforming a non-linear relationship into Y = mX + c so a straight-line graph can be used."]],
    p: [
      ["Logarithms and exponentials", "Use ln(ab)=ln a+ln b, ln(a/b)=ln a−ln b and ln(aᵏ)=k ln a. A logarithm argument must be positive. The graphs y=eˣ and y=ln x are reflections in y=x; eˣ>0 for all real x, while ln x has vertical asymptote x=0.", ["Do not split ln(a+b).", "When taking logs of both sides, first ensure both sides are positive."]],
      ["Solving equations and inequalities", "Try writing both sides with a common base. Otherwise isolate the exponential expression and take logarithms. For inequalities, remember that eˣ and ln x are increasing, but a base a with 0<a<1 reverses the inequality when comparing exponents.", ["Keep logarithms exact until the final numerical evaluation.", "Reject roots that make any log argument non-positive."]],
      ["Linearising power laws", "For y=Axⁿ, take logs to obtain ln y = n ln x + ln A. A plot of ln y against ln x has gradient n and intercept ln A, so A=eⁱⁿᵗᵉʳᶜᵉᵖᵗ. Units and the choice of transformed axes matter.", ["Gradient is the exponent, not the coefficient A.", "Back-transform the intercept before reporting A."]],
      ["Linearising exponential laws", "For y=Abˣ, ln y = x ln b + ln A. A plot of ln y against x has gradient ln b. In continuous growth y=Aeᵏˣ, the gradient is k. A negative k models decay; half-life solves eᵏᵗ=1/2.", ["State the transformed variables used on each axis.", "Interpret constants using the original model, not only the straight line."]]
    ],
    f: [["Log laws", "ln(ab)=ln a+ln b; ln(a/b)=ln a−ln b; ln(aᵏ)=k ln a"], ["Power-law linearisation", "y=Axⁿ ⇒ ln y = n ln x + ln A"], ["Exponential linearisation", "y=Abˣ ⇒ ln y = x ln b + ln A"], ["Continuous model", "y=Aeᵏˣ"]],
    r: [["How is y=Axⁿ linearised?", "Plot ln y against ln x; the gradient is n and the intercept is ln A."], ["What restriction applies to ln f(x)?", "f(x) must be strictly positive."], ["How do you recover A from an intercept c=ln A?", "Use A=eᶜ."], ["What does k<0 mean in y=Aeᵏᵗ?", "The quantity decays exponentially as t increases."]],
    t: ["Write the log-domain restriction before solving an equation containing ln.", "Label transformed graph axes explicitly, including whether common logs or natural logs were used."],
    m: ["Using ln(a+b)=ln a+ln b, which is false.", "Reporting ln A instead of A from a graph intercept.", "Rounding a logarithmic intermediate value too early."],
    rel: ["3.4", "3.8"]
  },
  "3.3": {
    s: ["Use sec, cosec and cot and their identities and graphs.", "Use compound-angle and double-angle identities to simplify expressions and solve equations.", "Express a sin θ + b cos θ as R sin(θ+α) or R cos(θ−α).", "Find exact values, solutions in a stated interval, and maximum/minimum values."],
    d: [["Secant", "sec θ = 1/cos θ."], ["Cosecant", "cosec θ = 1/sin θ."], ["Cotangent", "cot θ = cos θ/sin θ = 1/tan θ."], ["Compound angle", "An angle written as A±B so its sine, cosine or tangent can be expanded."], ["R-form", "A single shifted sine or cosine equal to a linear combination of sin θ and cos θ."]],
    p: [
      ["Reciprocal functions and identities", "Know sec²θ=1+tan²θ and cosec²θ=1+cot²θ. Domain exclusions occur wherever the denominator is zero. Sketching the reciprocal graphs helps determine asymptotes, periods and all solutions.", ["sec and cosec have range y≤−1 or y≥1.", "cot θ has period π radians."]],
      ["Compound and double angles", "Use sin(A±B)=sin A cos B±cos A sin B and cos(A±B)=cos A cos B∓sin A sin B. From these derive sin2A=2sinAcosA and the three useful forms of cos2A.", ["Choose cos2A=1−2sin²A or 2cos²A−1 to eliminate the unwanted function.", "Preserve signs carefully in cos(A±B)."]],
      ["The R-form", "For a sinθ+b cosθ=R sin(θ+α), compare coefficients: Rcosα=a and Rsinα=b, so R=√(a²+b²). The interval/quadrant for α must match both signs. The form makes extrema and equations easier.", ["Maximum is R and minimum is −R before any vertical shift.", "Use a sketch to decide which inverse-trig solution is appropriate."]],
      ["Solving trigonometric equations", "Reduce to one trig function or R-form, solve the basic equation, then generate every solution in the requested interval. Work in radians unless degrees are stated. Check any values lost by dividing by sinθ or cosθ.", ["Write the general symmetry pattern before filtering the interval.", "Do not cancel a trig factor unless its zero case has been considered."]]
    ],
    f: [["Pythagorean identities", "sec²θ=1+tan²θ; cosec²θ=1+cot²θ"], ["Compound angles", "sin(A±B)=sinAcosB±cosAsinB; cos(A±B)=cosAcosB∓sinAsinB"], ["Double angles", "sin2A=2sinAcosA; cos2A=cos²A−sin²A"], ["R magnitude", "R=√(a²+b²)"]],
    r: [["How do you find R in a sinθ+b cosθ?", "R=√(a²+b²)."], ["Which identity converts 1+tan²θ?", "1+tan²θ=sec²θ."], ["Why must divided trig factors be checked separately?", "A factor may be zero, and dividing by it would discard valid solutions."], ["What is the range of R sin(θ+α)+c?", "From c−R to c+R inclusive."]],
    t: ["Keep the calculator in the angle mode used by the question.", "List solutions in increasing order and include endpoints only when they satisfy the equation."],
    m: ["Using the wrong sign in the cosine compound-angle formula.", "Finding one inverse-trig value but not the other solutions in the interval.", "Choosing α without checking the signs of sin α and cos α."],
    rel: ["3.4", "3.5"]
  },
  "3.4": {
    s: ["Differentiate eˣ, ln x, trigonometric functions and tan⁻¹x, including composite functions.", "Use product, quotient and chain rules accurately.", "Differentiate implicit and parametric relations.", "Find tangents, normals, stationary points and rates of change."],
    d: [["Implicit relation", "An equation connecting x and y without y isolated as a function of x."], ["Parametric equations", "Equations x=f(t), y=g(t) describing a curve through a parameter t."], ["Stationary point", "A point where dy/dx=0."], ["Normal", "A line perpendicular to the tangent at the point of contact."], ["Chain rule", "A rule for differentiating a composite function by multiplying derivatives through its layers."]],
    p: [
      ["Core derivatives and chain rule", "Memorise d(eˣ)/dx=eˣ, d(ln x)/dx=1/x, d(sin x)/dx=cos x, d(cos x)/dx=−sin x, d(tan x)/dx=sec²x and d(tan⁻¹x)/dx=1/(1+x²). For f(g(x)), multiply f′(g(x)) by g′(x).", ["Trig derivative formulae assume radians.", "ln|u| differentiates to u′/u wherever u≠0."]],
      ["Products and quotients", "For y=uv, y′=u′v+uv′. For y=u/v, y′=(vu′−uv′)/v². Label u and v first and simplify after differentiating, especially when a second derivative is required.", ["The quotient-rule numerator order is denominator×derivative of numerator minus numerator×derivative of denominator.", "A product can sometimes be rewritten to use the chain rule more cleanly."]],
      ["Implicit differentiation", "Differentiate every term with respect to x and attach dy/dx whenever a y-term is differentiated. Collect all dy/dx terms on one side and factor. Substitute the point only after obtaining a usable derivative expression.", ["d(y²)/dx=2y(dy/dx).", "For xy use the product rule: d(xy)/dx=y+x(dy/dx)."]],
      ["Parametric differentiation", "If x=f(t) and y=g(t), then dy/dx=(dy/dt)/(dx/dt), provided dx/dt≠0. For d²y/dx², differentiate dy/dx with respect to t and divide by dx/dt again.", ["Find the parameter value corresponding to the stated point.", "Normal gradient is −1/(dy/dx) when the tangent gradient is non-zero."]]
    ],
    f: [["Product rule", "d(uv)/dx=u(dv/dx)+v(du/dx)"], ["Quotient rule", "d(u/v)/dx=(v·du/dx−u·dv/dx)/v²"], ["Parametric derivative", "dy/dx=(dy/dt)/(dx/dt)"], ["Second parametric derivative", "d²y/dx²=[d(dy/dx)/dt]/(dx/dt)"], ["Inverse tangent", "d(tan⁻¹x)/dx=1/(1+x²)"]],
    r: [["How is dy/dx found from x=f(t), y=g(t)?", "Divide dy/dt by dx/dt."], ["What happens when y² is differentiated implicitly?", "It becomes 2y(dy/dx)."], ["What is the normal gradient?", "It is the negative reciprocal of the tangent gradient, when defined."], ["Why are radians essential for trig differentiation?", "The standard derivative formulae for sin x, cos x and tan x are valid without extra factors only in radians."]],
    t: ["Show the derivative formula before substituting numerical coordinates.", "For stationary points, use the derivative sign or d²y/dx² to classify when asked."],
    m: ["Forgetting dy/dx when differentiating a y-term implicitly.", "Using (du/dx)/(dv/dx) as the quotient rule.", "Stopping at d(dy/dx)/dt instead of dividing by dx/dt for d²y/dx²."],
    rel: ["3.5", "3.8"]
  },
  "3.5": {
    s: ["Integrate exponential, logarithmic and trigonometric forms using reverse differentiation.", "Use substitution, integration by parts and partial fractions.", "Evaluate definite integrals and recognise when bounds must change.", "Select and combine techniques for unfamiliar integrands."],
    d: [["Substitution", "Replacing an expression by a new variable to simplify an integral."], ["Integration by parts", "A product-rule rearrangement used to integrate products."], ["Definite integral", "A signed accumulated quantity evaluated between fixed limits."], ["Partial fractions", "A decomposition that turns a rational expression into simpler integrable terms."], ["Constant of integration", "The arbitrary constant required for an indefinite integral."]],
    p: [
      ["Standard reverse derivatives", "Recognise ∫f′(x)/f(x) dx=ln|f(x)|+C and ∫eᵃˣ⁺ᵇ dx=eᵃˣ⁺ᵇ/a+C. Similarly account for the inner derivative in sin(ax+b), cos(ax+b) and sec²(ax+b).", ["Use ln|f(x)| unless the domain guarantees f(x)>0.", "Differentiate the result mentally to check the scale factor."]],
      ["Substitution", "Choose u for the repeated inner expression, calculate du, and rewrite every x and dx term. For definite integrals either change both limits to u-values or return fully to x before applying the original limits.", ["A substitution is incomplete if x remains in the new integrand.", "Write new bounds beside u=… to avoid mixing variables."]],
      ["Integration by parts", "Use ∫u(dv/dx)dx=uv−∫v(du/dx)dx. Choose u so it becomes simpler when differentiated—commonly logarithmic or algebraic before trig/exponential. Repeated use may be needed.", ["For ∫ln x dx, take dv/dx=1.", "Keep brackets around the second integral to protect the minus sign."]],
      ["Partial fractions and trig identities", "Decompose rational functions before integrating; repeated linear terms lead to powers such as (ax+b)⁻². For sin²x or cos²x use double-angle identities. Some integrals need a sequence: algebraic division, partial fractions, then standard forms.", ["A 1/(x²+a²) term integrates to an arctangent form.", "Simplify the integrand before choosing a method."]]
    ],
    f: [["Integration by parts", "∫u(dv/dx)dx=uv−∫v(du/dx)dx"], ["Log derivative", "∫f′(x)/f(x) dx=ln|f(x)|+C"], ["Inverse tangent form", "∫1/(x²+a²) dx=(1/a)tan⁻¹(x/a)+C"], ["Trig squares", "sin²x=(1−cos2x)/2; cos²x=(1+cos2x)/2"]],
    r: [["When should limits be changed in substitution?", "When the integral is rewritten in the new variable; otherwise return completely to x before using x-limits."], ["What is a strong choice for u in ∫x eˣ dx?", "Choose u=x because differentiation simplifies it, and integrate eˣ as dv/dx."], ["Which pattern gives a logarithm?", "An integrand of the form f′(x)/f(x)."], ["How can ∫cos²x dx be made integrable?", "Use cos²x=(1+cos2x)/2."]],
    t: ["Include +C for every indefinite integral, but not for a definite value.", "After a difficult integral, differentiate your antiderivative to verify it."],
    m: ["Using old x-limits after changing the variable to u.", "Missing the inner derivative scale factor.", "Applying integration by parts when a simple substitution is available."],
    rel: ["3.1", "3.4", "3.8"]
  },
  "3.6": {
    s: ["Locate roots using graphs or a sign change.", "Relate xₙ₊₁=F(xₙ) to the equation being solved.", "Carry out iterations accurately and recognise possible failure to converge.", "Justify a root to a prescribed degree of accuracy."],
    d: [["Root", "A value α for which f(α)=0."], ["Iteration", "Repeatedly applying xₙ₊₁=F(xₙ) to generate approximations."], ["Convergence", "The approximations approach a fixed limiting value."], ["Sign change", "f(a) and f(b) have opposite signs, guaranteeing at least one root in (a,b) when f is continuous."], ["Fixed point", "A value α satisfying α=F(α)."]],
    p: [
      ["Locating a root", "For continuous f, calculate f(a) and f(b). If f(a)f(b)<0, at least one root lies between a and b. A graph helps choose a sensible interval, but a sign change alone does not prove uniqueness.", ["State continuity when giving a formal sign-change justification.", "An even-multiplicity root may touch the axis without changing sign."]],
      ["Building an iteration", "Rearrange f(x)=0 into x=F(x), then use xₙ₊₁=F(xₙ). Different rearrangements can converge, oscillate or diverge. Use the starting value given and retain calculator precision through the table.", ["Show enough consecutive values for the examiner to follow the process.", "Do not replace F(xₙ) with f(xₙ)."]],
      ["Understanding convergence", "A convergent sequence settles near a fixed point α where α=F(α). Cobweb thinking explains why some iterations move toward the intersection y=F(x), y=x and others move away; the syllabus expects recognition of failure even if the derivative test is not required.", ["Oscillation may still converge if its size shrinks.", "A calculator error message can indicate the rearrangement leaves its valid domain."]],
      ["Proving the stated accuracy", "A rounded decimal needs a bracket around the true root. For a value r correct to k decimal places, test the half-unit boundaries r±0.5×10⁻ᵏ and show f changes sign there, assuming continuity and a single relevant root.", ["Repeated equal displayed iterates suggest accuracy but do not by themselves prove it.", "Use unrounded boundaries and function values."]]
    ],
    f: [["Sign-change test", "f(a)f(b)<0 ⇒ at least one root in (a,b), if f is continuous"], ["Iteration", "xₙ₊₁=F(xₙ)"], ["Rounding bracket", "r−0.5×10⁻ᵏ < α < r+0.5×10⁻ᵏ"]],
    r: [["What must accompany a sign change to guarantee a root?", "Continuity of f on the interval."], ["What equation does the limit of xₙ₊₁=F(xₙ) satisfy?", "The fixed-point equation α=F(α)."], ["How do you justify a root to 3 decimal places?", "Show a sign change at the two rounding boundaries r±0.0005, with the relevant continuity/uniqueness context."], ["Can a root exist without a sign change?", "Yes; an even-multiplicity root can touch the axis and turn back."]],
    t: ["Keep full calculator precision during iteration and round only the requested final value.", "Write f(a) and f(b) with their signs, not only the product."],
    m: ["Claiming a sign change proves there is exactly one root.", "Using rounded iterates inside later iterations.", "Proving accuracy with endpoints that do not match the requested rounding interval."],
    rel: ["3.1", "3.2"]
  },
  "3.7": {
    s: ["Use 2D and 3D position, displacement and unit vectors.", "Write and interpret r=a+λb for a straight line.", "Determine whether two lines are parallel, intersecting or skew.", "Use the scalar product to find angles and perpendicular projections."],
    d: [["Position vector", "The vector from the origin to a point."], ["Direction vector", "Any non-zero vector parallel to a line."], ["Unit vector", "A vector of magnitude 1."], ["Scalar product", "a·b=|a||b|cosθ, producing a scalar."], ["Skew lines", "Non-parallel lines in 3D that do not intersect."]],
    p: [
      ["Vector operations", "For a=(a₁,a₂,a₃), |a|=√(a₁²+a₂²+a₃²) and the unit vector in its direction is a/|a|. If A and B have position vectors a and b, then AB=b−a and the midpoint is (a+b)/2.", ["A displacement vector has direction; distance is its magnitude.", "Use exact radicals unless a decimal is requested."]],
      ["Vector equations of lines", "The line through point A with position vector a and direction b is r=a+λb. Through A and B, use direction b−a. Direction vectors can be scalar multiples and still describe parallel lines.", ["The parameter is a scalar, not a vector component.", "Read a point from the fixed vector and direction from the coefficient of λ."]],
      ["Intersections and skew lines", "Equate the x, y and z components of two line equations. Solve two equations for the two parameters, then test the third. If it fails, non-parallel lines are skew; if directions are multiples, test whether a point lies on both lines.", ["Always perform the third-component check.", "Report the point of intersection, not only parameter values."]],
      ["Scalar products and perpendicularity", "Compute a·b=a₁b₁+a₂b₂+a₃b₃. Perpendicular vectors have dot product 0. For an angle use cosθ=(a·b)/(|a||b|); for the acute angle between lines, reverse a direction if necessary or use |a·b|.", ["A foot of a perpendicular lies on the line and its displacement to the external point has zero dot product with the line direction.", "Shortest distance between skew lines is outside this syllabus."]]
    ],
    f: [["Magnitude", "|a|=√(a₁²+a₂²+a₃²)"], ["Line", "r=a+λb"], ["Scalar product", "a·b=a₁b₁+a₂b₂+a₃b₃=|a||b|cosθ"], ["Perpendicularity", "a·b=0"]],
    r: [["How do you form AB from position vectors?", "AB=OB−OA."], ["How do you distinguish intersecting and skew lines?", "Solve two component equations for the parameters and check the third; failure for non-parallel lines means skew."], ["What does a·b=0 show?", "The non-zero vectors are perpendicular."], ["How is the foot from P to r=a+λb found?", "Let Q=a+λb and solve (P−Q)·b=0 for λ."]],
    t: ["Use different parameter letters for different lines.", "For line angles, state whether the question wants the acute angle or a directed angle."],
    m: ["Assuming two non-parallel 3D lines must intersect.", "Solving only two components and skipping the third.", "Using position vectors instead of direction vectors in the angle formula."],
    rel: ["3.4", "4.1"]
  },
  "3.8": {
    s: ["Translate rate-of-change statements into first-order differential equations.", "Solve separable differential equations by integration.", "Use an initial condition to find a particular solution.", "Interpret constants and solutions in the modelling context."],
    d: [["Differential equation", "An equation involving a function and one or more of its derivatives."], ["Separable", "A first-order equation that can be rearranged with all y terms with dy and all x terms with dx."], ["General solution", "A family of solutions containing an arbitrary constant."], ["Initial condition", "A known value such as y=y₀ when x=x₀ that selects one solution."], ["Constant of proportionality", "A constant k introduced when a rate is said to be proportional to a quantity."]],
    p: [
      ["Forming the model", "Translate phrases literally: 'rate of increase of y is proportional to y' gives dy/dt=ky; 'rate is proportional to the remaining amount' gives dM/dt=k(M₀−M). Choose the sign from whether the quantity increases or decreases.", ["Define variables and units before forming the equation.", "A constant of proportionality is not automatically positive if its sign is already built into the model."]],
      ["Separating variables", "From dy/dx=g(x)h(y), rearrange dy/h(y)=g(x)dx and integrate both sides. Separation must happen before integration. Use logarithmic absolute values where needed.", ["Never move dy/dx as though dy and dx were ordinary numbers without showing a valid separated form.", "Check that dividing by h(y) has not discarded an equilibrium solution h(y)=0."]],
      ["Applying initial conditions", "After integrating, include a constant and substitute the condition. Sometimes exponentiating produces a multiplicative constant more naturally. Leave an implicit solution if the question allows it; otherwise isolate y.", ["Apply the condition to the integrated equation, not the original derivative.", "Use exact constants until the final numerical answer."]],
      ["Interpreting and checking", "Differentiate the proposed solution to check it satisfies the differential equation and initial condition. In context, reject impossible branches and describe long-term behaviour, limiting values, monotonicity or the meaning of k.", ["A mathematical solution may violate physical restrictions such as mass≥0.", "State units for time constants and rates."]]
    ],
    f: [["Separation pattern", "dy/dx=g(x)h(y) ⇒ ∫[1/h(y)]dy=∫g(x)dx"], ["Exponential growth/decay", "dy/dt=ky ⇒ y=Aeᵏᵗ"], ["Newton-style approach", "dy/dt=k(L−y) ⇒ y=L+Ae⁻ᵏᵗ when k>0"]],
    r: [["What comes before integrating a separable equation?", "Rearrange so all y terms accompany dy and all x terms accompany dx."], ["What does an initial condition do?", "It determines the arbitrary constant and selects a particular solution."], ["What solution can be lost by dividing by h(y)?", "Any constant equilibrium solution satisfying h(y)=0."], ["How do you check a differential-equation solution?", "Differentiate it and substitute into both the equation and the initial condition."]],
    t: ["State the proportionality equation before solving it.", "Interpret the sign and units of the constant in the original context."],
    m: ["Omitting the integration constant.", "Using ln f(y) without an absolute value when the sign is not known.", "Accepting a negative time, population or mass that is impossible in context."],
    rel: ["3.2", "3.5"]
  },
  "3.9": {
    s: ["Use Cartesian and polar forms, modulus, argument and conjugates.", "Perform arithmetic and use conjugate-pair roots for real polynomials.", "Multiply/divide in polar form and find exact square roots.", "Represent equations and inequalities as loci on an Argand diagram."],
    d: [["Complex number", "z=x+iy, where i²=−1 and x,y are real."], ["Conjugate", "For z=x+iy, z*=x−iy."], ["Modulus", "|z|=√(x²+y²), the distance from the origin."], ["Argument", "arg z is the directed angle from the positive real axis to z."], ["Argand diagram", "A plane with real part horizontally and imaginary part vertically."]],
    p: [
      ["Cartesian arithmetic", "Add real and imaginary parts separately and use i²=−1 when multiplying. To divide by c+id, multiply numerator and denominator by c−id so the denominator becomes c²+d². Equality requires both real parts and imaginary parts to match.", ["z z*=|z|².", "Real-coefficient polynomial roots occur in conjugate pairs."]],
      ["Polar form", "Write z=r(cosθ+i sinθ), where r=|z| and θ=arg z. On multiplication, multiply moduli and add arguments; on division, divide moduli and subtract arguments. Give the argument in the interval requested.", ["Use atan2 thinking or a sketch to choose the correct quadrant.", "The principal argument is commonly −π<θ≤π."]],
      ["Square roots and equations", "For w²=z, let w=a+ib and compare real and imaginary parts, using a²+b²=|z| as a second relation. The two roots are opposites. For polynomial questions, include the conjugate of any given non-real root, form the quadratic factor and divide.", ["Show exact Cartesian working for square roots.", "Check by squaring the final roots."]],
      ["Loci", "|z−a|=r is a circle centred at a; |z−a|<r is its interior. |z−a|=|z−b| is the perpendicular bisector of AB. arg(z−a)=α is a ray from a, with the initial point excluded.", ["Use solid or dashed boundaries to distinguish inclusive and strict inequalities.", "Shade only after testing a simple point."]]
    ],
    f: [["Modulus", "|x+iy|=√(x²+y²)"], ["Conjugate product", "zz*=|z|²"], ["Polar product", "r₁cisθ₁·r₂cisθ₂=r₁r₂cis(θ₁+θ₂)"], ["Polar quotient", "r₁cisθ₁/(r₂cisθ₂)=(r₁/r₂)cis(θ₁−θ₂)"]],
    r: [["Why multiply by a conjugate when dividing?", "It makes the denominator real because (c+id)(c−id)=c²+d²."], ["What locus is |z−a|=r?", "A circle centred at a with radius r."], ["What happens to arguments when complex numbers are divided?", "Subtract the divisor's argument from the numerator's argument."], ["If a real polynomial has root 2+3i, what else is a root?", "2−3i, its conjugate."]],
    t: ["Draw a small Argand sketch before fixing an argument quadrant.", "For loci, label centre, radius, boundary inclusion and excluded points."],
    m: ["Using arctan(y/x) without correcting the quadrant.", "Forgetting that square roots occur as ±w.", "Drawing arg(z−a)=α as a full line instead of a ray."],
    rel: ["3.1", "3.3", "3.7"]
  },
  "4.1": {
    s: ["Identify weight, normal reaction, tension and friction on a force diagram.", "Resolve forces parallel and perpendicular to a chosen direction.", "Apply equilibrium conditions to a particle.", "Use F≤μR and F=μR at limiting equilibrium."],
    d: [["Equilibrium", "A state with zero resultant force, so acceleration is zero."], ["Normal reaction", "The contact force perpendicular to a surface."], ["Friction", "A contact force opposing actual or impending relative motion."], ["Limiting equilibrium", "The state just before slipping, when friction reaches μR."], ["Particle model", "An object treated as having mass but negligible size and rotation."]],
    p: [["Building the force diagram", "Isolate one particle and draw every external force: weight mg vertically down, normal reaction perpendicular to contact, tension along a string and friction along a rough surface. Never draw motion or acceleration as a force.", ["Choose axes parallel and perpendicular to an incline.", "Label each force once with a clear direction."]], ["Resolving and equilibrium", "For equilibrium, the vector sum of forces is zero. Resolve independently in two perpendicular directions. On an incline of angle θ, weight components are mg sinθ down the plane and mg cosθ into the plane.", ["Equilibrium does not mean no forces; it means they balance.", "Use exact trig values until the end."]], ["Friction", "Friction adjusts up to a maximum μR. Use F=μR only when the particle is on the point of slipping or in limiting equilibrium. Decide its direction by imagining how the particle would move without friction.", ["In non-limiting equilibrium, F may be less than μR.", "The normal reaction is not always mg."]], ["Connected or angled forces", "When a string or applied force is angled, resolve it before writing equations. A vertical component can change R and therefore the maximum friction. Check that any calculated friction satisfies F≤μR.", ["A pull with an upward component reduces R.", "State whether the model is smooth or rough."]]],
    f: [["Weight", "W=mg"], ["Equilibrium", "ΣFₓ=0 and ΣFᵧ=0"], ["Friction law", "F≤μR; at limiting equilibrium F=μR"], ["Incline components", "mg sinθ parallel; mg cosθ perpendicular"]],
    r: [["When may F=μR be used?", "Only at limiting equilibrium or when the question states the friction is limiting."], ["Which way does friction act?", "Opposite actual or impending relative motion between the surfaces."], ["What does equilibrium imply about resultant force?", "The resultant is zero in every direction."], ["Why can R differ from mg?", "Other forces may have perpendicular or vertical components, and an incline changes the resolution."]],
    t: ["Begin every mechanics solution with a separate free-body diagram.", "After solving, check signs and whether the friction inequality is physically valid."],
    m: ["Setting friction equal to μR automatically.", "Drawing acceleration as a force.", "Assuming R=mg on an incline or with an angled pull."],
    rel: ["4.4", "4.5"]
  },
  "4.2": {
    s: ["Use displacement, velocity and acceleration with consistent signs.", "Interpret displacement–time and velocity–time graphs.", "Use differentiation and integration between s, v and a.", "Apply constant-acceleration formulae, including vertical motion under gravity."],
    d: [["Displacement", "Signed change of position from a reference point."], ["Velocity", "Rate of change of displacement."], ["Acceleration", "Rate of change of velocity."], ["Speed", "Magnitude of velocity."], ["Constant acceleration", "Motion for which acceleration has a fixed value over the interval."]],
    p: [["Signs and variables", "Choose one positive direction and keep it throughout. Displacement and velocity can be negative; speed and distance cannot. Turning points occur when v=0 and the sign of v changes.", ["State the positive direction in vertical-motion work.", "A negative acceleration does not always mean slowing down."]], ["Motion graphs", "Gradient of an s–t graph is velocity; gradient of a v–t graph is acceleration; signed area under v–t is displacement. Total distance requires adding the magnitudes of areas or splitting where v changes sign.", ["Horizontal v–t segments mean constant velocity.", "An area below the time axis contributes negative displacement."]], ["Calculus links", "Use v=ds/dt and a=dv/dt=v(dv/ds). Integrate acceleration to find velocity and integrate velocity to find displacement, applying initial conditions after each integration.", ["The v dv/ds form is useful when time is absent.", "Include constants of integration."]], ["SUVAT and gravity", "Use v=u+at, s=ut+½at², v²=u²+2as, and s=(u+v)t/2 only on an interval of constant acceleration. For free vertical motion take acceleration as ±g according to the chosen positive direction.", ["At maximum height v=0, not a=0.", "Use g=10 m s⁻² in this component unless told otherwise."]]],
    f: [["Calculus", "v=ds/dt; a=dv/dt=v·dv/ds"], ["SUVAT 1", "v=u+at"], ["SUVAT 2", "s=ut+½at²"], ["SUVAT 3", "v²=u²+2as"], ["Average velocity", "s=(u+v)t/2"]],
    r: [["What is the area under a velocity–time graph?", "Signed displacement."], ["How is total distance found when velocity changes sign?", "Split at v=0 and add the magnitudes of the displacements."], ["What is acceleration at maximum height?", "It is still g downward; only velocity is zero."], ["When are SUVAT formulae valid?", "Only while acceleration is constant over the interval considered."]],
    t: ["Write the selected SUVAT equation before substituting values.", "Split multi-stage motion into intervals and carry final conditions forward."],
    m: ["Treating displacement and distance as identical.", "Using a SUVAT formula when acceleration varies.", "Changing the positive direction halfway through a solution."],
    rel: ["4.4", "4.5"]
  },
  "4.3": {
    s: ["Use linear momentum p=mv as a vector in one dimension.", "Apply conservation of momentum to direct impacts.", "Handle particles that coalesce after collision.", "Interpret signs and check whether the proposed post-collision motion is possible."],
    d: [["Linear momentum", "Mass multiplied by velocity; its direction follows the velocity."], ["Direct impact", "A collision in which motion is along one straight line."], ["Conservation of momentum", "Total momentum is unchanged when external impulse during the interaction is negligible."], ["Coalescence", "Bodies join and move with a common velocity after impact."], ["System", "The collection of bodies chosen for a conservation equation."]],
    p: [["Momentum as a vector", "Choose a positive direction and write each momentum as mv with a signed velocity. Momentum has units kg m s⁻¹. A negative result means motion opposite to the chosen direction, not negative speed.", ["Mass is always positive.", "Use velocities immediately before and immediately after impact."]], ["Conservation equation", "For an isolated impact, total momentum before equals total momentum after. Include every body in the chosen system and keep the same positive direction on both sides.", ["Internal impact forces cancel in the system total.", "External forces are neglected only over the short collision time."]], ["Coalescing particles", "If masses m₁ and m₂ stick together, their final mass is m₁+m₂ and they share velocity v: m₁u₁+m₂u₂=(m₁+m₂)v. The kinetic energy usually decreases, even though momentum is conserved.", ["Do not conserve kinetic energy unless justified.", "Check whether v lies between the incoming signed velocities when appropriate."]], ["Scope and interpretation", "This component examines one-dimensional direct impact and conservation. Impulse and coefficient of restitution are not required by the 2026–2027 Paper 4 syllabus. Focus on a clean before/after diagram and a signed momentum equation.", ["Report direction with the final velocity.", "A body may reverse direction after impact."]]],
    f: [["Momentum", "p=mv"], ["Conservation", "Σ(momentum before)=Σ(momentum after)"], ["Coalescence", "m₁u₁+m₂u₂=(m₁+m₂)v"]],
    r: [["Why are velocities signed in momentum work?", "Momentum is a vector, so direction must be represented."], ["What common velocity applies after coalescence?", "Both bodies move with one velocity v and combined mass m₁+m₂."], ["Is kinetic energy always conserved in Paper 4 impacts?", "No. Momentum is conserved for the isolated system; kinetic energy may be lost."], ["Are impulse and restitution required here?", "No; they are outside the stated 2026–2027 Mechanics content."]],
    t: ["Draw a before/after line diagram with arrows before writing momentum equations.", "State the final direction when a calculated velocity is negative."],
    m: ["Using speeds without signs.", "Forgetting to combine masses when particles stick.", "Assuming momentum conservation means kinetic-energy conservation."],
    rel: ["4.2", "4.4"]
  },
  "4.4": {
    s: ["Apply Newton's laws to particles of constant mass.", "Use W=mg and include friction, tension or thrust correctly.", "Solve motion on rough inclines and vertical lines.", "Model connected particles with a light inextensible string and smooth pulley."],
    d: [["Resultant force", "The vector sum of all external forces on a body."], ["Newton's second law", "For constant mass, resultant force equals ma."], ["Tension", "A pulling force transmitted by a taut string."], ["Light string", "A string whose mass is neglected, allowing common tension in the ideal model."], ["Inextensible string", "A string of fixed length, so connected particles share acceleration magnitude while taut."]],
    p: [["Applying F=ma", "Draw a force diagram for one body at a time, choose a positive direction, then write ΣF=ma in that direction. Forces opposite the positive direction enter negatively; acceleration uses the same sign convention.", ["F=ma uses resultant force, not any single force.", "Equilibrium is the special case a=0."]], ["Vertical and inclined motion", "Resolve weight into mg sinθ along an incline and mg cosθ perpendicular. Friction opposes motion and can make upward and downward accelerations different. In vertical motion, weight remains downward throughout.", ["Use R to determine friction where needed.", "At a turning point velocity is zero but the force and acceleration need not be."]], ["Connected particles", "For a light inextensible string over a smooth pulley, use one acceleration magnitude and common tension. Write a separate F=ma equation for each particle, then solve simultaneously. A whole-system equation can remove internal tension as a check.", ["Do not put forces from two different bodies on one free-body diagram.", "Check that a computed tension is non-negative and the string remains taut."]], ["Towing and thrust", "A car and trailer have common acceleration while connected. Treat the tow-bar force as tension if pulling and thrust/compression if pushing. Use the whole system for acceleration, then one body for the connector force.", ["Resistance may act separately on each body.", "Newton's third-law pair acts on different bodies."]]],
    f: [["Newton's second law", "ΣF=ma"], ["Weight", "W=mg"], ["Rough contact", "F≤μR"], ["Connected system", "common |a| and common T for a light taut string over a smooth pulley"]],
    r: [["What belongs on the left of F=ma?", "The signed resultant of all forces on that one body."], ["Why do ideal connected particles share acceleration magnitude?", "The taut string is inextensible, so its length cannot change."], ["How can tension be eliminated?", "Apply F=ma to the whole connected system; tension is internal."], ["Can acceleration differ going up and down a rough incline?", "Yes, because friction reverses direction while gravity's component does not."]],
    t: ["Use one equation per body and label which body it describes.", "Check model assumptions—light string, smooth pulley, taut connection—before equating tensions or accelerations."],
    m: ["Using F=ma for a single force instead of the resultant.", "Giving connected particles opposite signed accelerations after already choosing their separate positive directions inconsistently.", "Including an action–reaction pair on the same body."],
    rel: ["4.1", "4.2", "4.5"]
  },
  "4.5": {
    s: ["Calculate work by a constant force at an angle to displacement.", "Use kinetic and gravitational potential energy.", "Apply work–energy and conservation of energy.", "Use average and instantaneous power, including P=Fv."],
    d: [["Work", "Energy transferred when a force acts through a displacement."], ["Kinetic energy", "Energy associated with motion, ½mv²."], ["Gravitational potential energy", "Energy associated with height, mgh relative to a chosen datum."], ["Power", "Rate of doing work or transferring energy."], ["Resistance", "A force opposing motion and dissipating mechanical energy."]],
    p: [["Work by a force", "For constant force F and displacement d with angle θ between them, work is Fd cosθ. Work is positive when the force helps motion, negative when it opposes, and zero when perpendicular.", ["Use the angle between force and displacement, not automatically the slope angle.", "Work has units joules."]], ["Energy stores", "Kinetic energy is ½mv² and gravitational potential change is mgΔh. Only height change matters for GPE, even on a curved path. Choose a convenient zero level and use energy differences consistently.", ["Speed enters KE squared.", "Mass cancels in some smooth gravity problems but not all."]], ["Work–energy principle", "Change in KE equals total work done by external forces. Equivalently, initial KE+GPE+work supplied equals final KE+GPE+energy dissipated. Include resistance as negative work or a positive loss, but not both.", ["Energy methods avoid time and often avoid resolving acceleration along a changing path.", "Mechanical energy is conserved only when no non-conservative work is done."]], ["Power", "Average power=work/time. Instantaneous power for a force parallel to motion is P=Fv. For a vehicle climbing at constant speed, driving power balances the rate of gain of GPE plus work against resistance.", ["If acceleration is present, include ma in the force balance before using P=Fv.", "Convert kW to W."]]],
    f: [["Work", "W=Fd cosθ"], ["Kinetic energy", "KE=½mv²"], ["GPE change", "ΔGPE=mgΔh"], ["Average power", "P=W/t"], ["Instantaneous power", "P=Fv", "For the force component along the velocity."]],
    r: [["When is work by a force zero?", "When the force is perpendicular to the displacement."], ["What does change in kinetic energy equal?", "The total work done by external forces."], ["Why does a curved smooth track still use mgh?", "Gravitational potential energy depends only on vertical height change."], ["When may P=Fv be used directly?", "For the force component acting in the direction of instantaneous motion."]],
    t: ["Write an energy ledger with initial, final, supplied and dissipated terms.", "Keep signs consistent—do not count resistance twice."],
    m: ["Using path length instead of vertical height in mgh.", "Using P=Fv with the total force when only one force's power is required.", "Conserving mechanical energy despite friction without including its work."],
    rel: ["4.1", "4.2", "4.4"]
  },
  "5.1": {
    s: ["Choose, draw and interpret statistical displays.", "Use cumulative frequency to estimate medians, quartiles and percentiles.", "Calculate mean, variance and standard deviation, including grouped/coded data.", "Compare distributions using measures of location and spread."],
    d: [["Frequency density", "Frequency divided by class width; histogram area represents frequency."], ["Interquartile range", "Q₃−Q₁, the spread of the middle 50%."], ["Standard deviation", "The square root of variance, measuring typical spread about the mean."], ["Cumulative frequency", "A running total of observations up to a boundary."], ["Outlier", "An observation unusually far from the rest; a common rule is below Q₁−1.5IQR or above Q₃+1.5IQR."]],
    p: [["Choosing a display", "Stem-and-leaf retains raw values, box plots compare location/spread, cumulative frequency supports percentiles, and histograms show continuous grouped distributions. Discuss what information each preserves or hides.", ["Use class boundaries for continuous data.", "A box width in a histogram is not a frequency by itself."]], ["Histograms", "For unequal class widths, vertical height is frequency density so bar area equals frequency. To recover frequency multiply density by class width. Label continuous boundaries and axes with units.", ["Do not leave gaps between continuous classes.", "A changed vertical scale must still preserve area ratios."]], ["Cumulative frequency", "Plot upper class boundaries against cumulative totals. Estimate Q₁, median and Q₃ at n/4, n/2 and 3n/4, reading horizontally to the curve then vertically to the value axis.", ["Graph estimates should match the graph's precision.", "Percentile p uses pn/100."]], ["Mean and variation", "Use x̄=Σx/n and variance=Σx²/n−x̄² for a population-style data set in this syllabus. For grouped data use class midpoints, so answers are estimates. Coding transforms totals and can simplify arithmetic.", ["Compare both centre and spread in context.", "A smaller spread means greater consistency, not necessarily better performance."]]],
    f: [["Frequency density", "frequency density=frequency/class width"], ["Mean", "x̄=Σx/n"], ["Variance", "Var=Σx²/n−x̄²"], ["Standard deviation", "σ=√Var"], ["Interquartile range", "IQR=Q₃−Q₁"]],
    r: [["What does histogram area represent?", "Frequency, so height must be frequency density when class widths differ."], ["Where is the median read on a cumulative-frequency graph?", "At cumulative frequency n/2."], ["Why are grouped-data statistics estimates?", "Every value in a class is represented by its class midpoint."], ["What two features should a comparison mention?", "A measure of location and a measure of spread, interpreted in context."]],
    t: ["Write units on graph axes and quote comparisons in the language of the data.", "Use unrounded variance before taking the square root."],
    m: ["Using frequency as histogram height for unequal widths.", "Comparing means without comparing spread.", "Using class limits instead of continuous class boundaries."],
    rel: ["6.4", "6.5"]
  },
  "5.2": {
    s: ["Distinguish permutations from combinations.", "Count arrangements with repeated objects.", "Handle adjacency, separation and positional restrictions.", "Use complementary counting and gap methods."],
    d: [["Permutation", "An ordered arrangement."], ["Combination", "An unordered selection."], ["Factorial", "n!=n(n−1)…1, with 0!=1."], ["Identical objects", "Objects whose interchange creates no new arrangement."], ["Complementary counting", "Counting all outcomes then subtracting forbidden outcomes."]],
    p: [["Order versus selection", "Use ⁿPᵣ=n!/(n−r)! when order matters and ⁿCᵣ=n!/[r!(n−r)!] when it does not. Many problems combine a selection stage with a later arrangement stage; multiply the stage counts.", ["Ask whether swapping two chosen objects changes the outcome.", "Explain each factor instead of presenting an unexplained product."]], ["Repeated objects", "For n objects with repeated groups of sizes a,b,…, the number of distinct linear arrangements is n!/(a!b!…). Dividing removes permutations that look identical.", ["Count the total number of letters carefully.", "Only divide for genuinely identical objects."]], ["Objects together or apart", "For objects that must stay together, treat the block as one object and multiply by internal orders. For 'not together', subtract together-cases from all arrangements. For separated identical objects, arrange the other objects and place them in gaps.", ["A block can appear in more than one internal order.", "Gap methods need enough available gaps."]], ["Position and grouping restrictions", "Handle fixed positions first, then arrange remaining objects. For rows or teams, select who occupies a group and then arrange within it if positions are distinct. Watch for double-counting when groups themselves are unlabelled.", ["Circular arrangements are outside this syllabus.", "Cases should be mutually exclusive before adding."]]],
    f: [["Permutation", "ⁿPᵣ=n!/(n−r)!"], ["Combination", "ⁿCᵣ=n!/[r!(n−r)!]"], ["Repeated objects", "n!/(a!b!⋯)"]],
    r: [["When is ⁿCᵣ appropriate?", "When selecting r objects and the order of selection does not matter."], ["How do you count arrangements where A and B stay together?", "Treat AB as one block, arrange the blocks, then multiply by 2 for AB or BA."], ["How is 'A and B not together' often counted?", "All arrangements minus arrangements in which they form a block."], ["Why divide by a! for a identical objects?", "Their a! internal permutations produce no visibly different arrangement."]],
    t: ["Annotate products with short labels such as choose, arrange and internal order.", "Check whether groups or positions are labelled before deciding about division."],
    m: ["Using permutations for a selection with no order.", "Forgetting internal arrangements of a block.", "Adding cases that overlap and double-count outcomes."],
    rel: ["5.3", "5.4"]
  },
  "5.3": {
    s: ["Use addition and multiplication rules in probability.", "Distinguish mutually exclusive and independent events.", "Calculate conditional probabilities.", "Model multi-stage situations with trees, Venn diagrams and combinations."],
    d: [["Mutually exclusive", "Events that cannot occur together, so P(A∩B)=0."], ["Independent", "Events where occurrence of one does not change the probability of the other."], ["Conditional probability", "P(A|B), the probability of A given B has occurred."], ["Complement", "A′, the event that A does not occur."], ["Sample space", "The set of possible elementary outcomes."]],
    p: [["Addition and multiplication", "For overlapping events, P(A∪B)=P(A)+P(B)−P(A∩B). Along successive branches multiply; across mutually exclusive complete routes add. Use complements for 'at least one'.", ["P(A′)=1−P(A).", "Without replacement, branch probabilities change."]], ["Exclusive versus independent", "Mutually exclusive non-zero events are not independent: if A occurs, B cannot. Test independence using P(A∩B)=P(A)P(B), or equivalently P(A|B)=P(A) when P(B)>0.", ["Do not infer independence from a diagram unless stated or shown.", "Zero-probability edge cases need care."]], ["Conditional probability", "Use P(A|B)=P(A∩B)/P(B). The denominator is the condition—the reduced sample space. Tree diagrams encode this because second-stage probabilities sit on branches after the condition is known.", ["Read 'given that' before deciding the denominator.", "Reverse conditionals P(A|B) and P(B|A) are generally different."]], ["Counting probability", "When elementary outcomes are equally likely, probability=favourable/total. Use combinations for unordered selections and carefully account for colours, categories or restrictions in both numerator and denominator.", ["A Venn diagram can expose intersections and complements.", "Check that final probabilities lie between 0 and 1."]]],
    f: [["Addition rule", "P(A∪B)=P(A)+P(B)−P(A∩B)"], ["Conditional probability", "P(A|B)=P(A∩B)/P(B)"], ["Independence", "P(A∩B)=P(A)P(B)"], ["Complement", "P(A′)=1−P(A)"]],
    r: [["Can two non-zero mutually exclusive events be independent?", "No; occurrence of one makes the other impossible."], ["What is the denominator of P(A|B)?", "P(B), because B is the restricted sample space."], ["How is 'at least one' often simplified?", "Use 1−P(none)."], ["What changes in a without-replacement tree?", "The second-stage totals and favourable counts depend on the first outcome."]],
    t: ["Define events in words before using symbols.", "Keep exact fractions through tree calculations where possible."],
    m: ["Confusing mutually exclusive with independent.", "Using P(A) rather than P(B) as the denominator of P(A|B).", "Keeping replacement probabilities unchanged in a without-replacement model."],
    rel: ["5.2", "5.4"]
  },
  "5.4": {
    s: ["Construct discrete probability distributions and find unknown constants.", "Calculate expectation and variance.", "Use and recognise binomial and geometric models.", "Find exact, cumulative and complementary probabilities."],
    d: [["Discrete random variable", "A variable taking separate countable numerical values."], ["Probability distribution", "A table or rule assigning a probability to each possible value."], ["Expectation", "The long-run mean E(X)."], ["Binomial distribution", "The number of successes in n independent fixed-probability trials."], ["Geometric distribution", "The trial number of the first success in independent trials with probability p."]],
    p: [["Distribution tables", "List every possible x and P(X=x), require each probability ≥0 and use ΣP(X=x)=1 to find constants. Then E(X)=ΣxP(X=x), E(X²)=Σx²P(X=x), and Var(X)=E(X²)−[E(X)]².", ["Probabilities, not x-values, must sum to 1.", "Variance cannot be negative."]], ["Binomial model", "X~B(n,p) requires a fixed number n, two outcomes per trial, constant success probability p and independent trials. Use P(X=r)=ⁿCᵣpʳ(1−p)ⁿ⁻ʳ, with mean np and variance np(1−p).", ["Translate 'at most', 'fewer than' and 'at least' carefully.", "Use complements for long upper tails."]], ["Geometric model", "For X~Geo(p), where X is the trial of first success, P(X=r)=p(1−p)ʳ⁻¹ and E(X)=1/p. The memoryless idea means after failures the chance of success on the next trial remains p.", ["The support begins at r=1, not 0.", "Do not use a fixed n in a geometric model."]], ["Using a calculator", "A calculator may evaluate cumulative probabilities, but the model, parameters and inequality conversion must be shown. For P(X>r), use 1−P(X≤r); for P(a≤X≤b), subtract cumulative values.", ["Check whether calculator cumulative commands include the endpoint.", "State the distribution before the probability statement."]]],
    f: [["Expectation", "E(X)=ΣxP(X=x)"], ["Variance", "Var(X)=E(X²)−[E(X)]²"], ["Binomial mass", "P(X=r)=ⁿCᵣpʳ(1−p)ⁿ⁻ʳ"], ["Binomial moments", "E(X)=np; Var(X)=np(1−p)"], ["Geometric mass", "P(X=r)=p(1−p)ʳ⁻¹"]],
    r: [["What four conditions support a binomial model?", "Fixed n, two outcomes, independent trials and constant success probability p."], ["What does a geometric variable count?", "The trial number on which the first success occurs."], ["How is Var(X) obtained from moments?", "E(X²)−[E(X)]²."], ["How can P(X≥r) be written cumulatively?", "1−P(X≤r−1)."]],
    t: ["Write X~B(n,p) or X~Geo(p) before calculating.", "Translate the words into an exact integer inequality before pressing the calculator."],
    m: ["Starting the geometric support at 0.", "Using binomial when the success probability changes.", "Writing P(X≥r)=1−P(X≤r)."],
    rel: ["5.3", "5.5", "6.1"]
  },
  "5.5": {
    s: ["Model a continuous variable with N(μ,σ²).", "Standardise and use normal tables/calculator probabilities.", "Find unknown values or parameters from probabilities.", "Use a continuity-corrected normal approximation to a binomial distribution."],
    d: [["Normal distribution", "A symmetric bell-shaped continuous distribution determined by mean μ and variance σ²."], ["Standardisation", "Converting X to Z=(X−μ)/σ with distribution N(0,1)."], ["Continuity correction", "Shifting a discrete boundary by 0.5 when using a continuous approximation."], ["Quantile", "A value below which a stated proportion of the distribution lies."], ["Variance", "σ²; the standard deviation is σ, not σ²."]],
    p: [["Normal model and sketches", "Write X~N(μ,σ²). The curve is symmetric about μ and total area is 1. Sketch and shade the required tail or interval before standardising; this catches complement and direction errors.", ["A point probability is zero for a continuous variable.", "Use σ=√variance in z-scores."]], ["Standardising", "For a boundary x, z=(x−μ)/σ. Use Φ(z)=P(Z≤z), symmetry Φ(−z)=1−Φ(z), and differences for intervals. Show the z-expression even when using a calculator directly.", ["Retain full precision in z until the final probability.", "Standardise both endpoints separately."]], ["Inverse normal questions", "Translate the stated area into a standard-normal quantile z, then solve x=μ+zσ. If μ or σ is unknown, each probability gives an equation. Use the sign of z based on whether the boundary lies below or above μ.", ["A small lower-tail probability has negative z.", "Standard deviation must be positive."]], ["Normal approximation to binomial", "For X~B(n,p), use Y~N(np,npq) when np>5 and nq>5, and apply continuity correction: X≤r becomes Y<r+0.5; X≥r becomes Y>r−0.5.", ["Use q=1−p.", "Apply the correction before standardising."]]],
    f: [["Standardisation", "Z=(X−μ)/σ"], ["Binomial approximation", "B(n,p)≈N(np,npq)"], ["Continuity examples", "P(X≤r)≈P(Y<r+0.5); P(X≥r)≈P(Y>r−0.5)"]],
    r: [["What is the second parameter in N(μ,σ²)?", "The variance σ²."], ["Which z corresponds to a boundary below μ?", "A negative z-score."], ["How is X≥12 continuity-corrected?", "Use the continuous boundary Y>11.5."], ["When is the binomial normal approximation acceptable here?", "When both np>5 and n(1−p)>5."]],
    t: ["Sketch and shade before using normal functions.", "Show the continuity-corrected boundary explicitly for approximation questions."],
    m: ["Dividing by variance instead of standard deviation.", "Forgetting continuity correction for a discrete-to-continuous approximation.", "Using the wrong tail after inverse normal."],
    rel: ["5.4", "6.1", "6.4"]
  },
  "6.1": {
    s: ["Calculate probabilities for X~Po(λ) and use E(X)=Var(X)=λ.", "Scale λ with time, area or volume.", "Recognise conditions for a Poisson process.", "Use Poisson approximations to binomial and normal approximations to Poisson."],
    d: [["Poisson distribution", "A count model for random events occurring independently at a constant average rate."], ["Parameter λ", "The expected number of events in the stated interval; it is also the variance."], ["Rate", "Expected events per unit time, length, area or volume."], ["Continuity correction", "A ±0.5 boundary adjustment for a continuous normal approximation."], ["Rare event", "An event with small probability per trial, supporting a Poisson approximation to binomial."]],
    p: [["Poisson probabilities", "If X~Po(λ), then P(X=r)=e⁻ˡᵃᵐᵇᵈᵃ λʳ/r!, r=0,1,2,… . Mean and variance are λ. Use cumulative or complementary probabilities for ranges.", ["The standard deviation is √λ.", "State the interval to which λ applies."]], ["Scaling the parameter", "A rate of c per unit gives λ=ct over t units, provided the rate is constant. Independent Poisson counts on disjoint intervals add, so parameters add too.", ["Scale λ, not an observed count.", "Check that units match before multiplying."]], ["Poisson approximation to binomial", "For X~B(n,p), use Po(np) when n is large and p small; Cambridge gives approximately n>50 and np<5. The approximation removes the fixed upper bound, so use only when the tail beyond n is negligible.", ["Use λ=np.", "No continuity correction is needed for Poisson-to-binomial because both are discrete."]], ["Normal approximation to Poisson", "When λ is large—approximately λ>15—use N(λ,λ) and apply a continuity correction. Standardise with standard deviation √λ.", ["Correct the integer boundary before finding z.", "Sketch the tail to avoid complement errors."]]],
    f: [["Poisson mass", "P(X=r)=e⁻λ λʳ/r!"], ["Poisson moments", "E(X)=Var(X)=λ"], ["Binomial approximation", "B(n,p)≈Po(np)"], ["Normal approximation", "Po(λ)≈N(λ,λ)"]],
    r: [["What are the mean and variance of Po(λ)?", "Both equal λ."], ["How does λ change when an interval triples?", "It triples if the average rate stays constant."], ["When is Poisson a useful binomial approximation?", "For large n and small p, approximately n>50 and np<5 in this syllabus."], ["What normal model approximates Po(λ)?", "N(λ,λ), with a continuity correction, when λ is sufficiently large."]],
    t: ["Write the newly scaled λ before computing any probability.", "Distinguish an exact Poisson model from a Poisson approximation in your notation."],
    m: ["Using λ as a standard deviation.", "Forgetting to scale λ when the interval changes.", "Applying a normal approximation without continuity correction."],
    rel: ["5.4", "5.5", "6.2"]
  },
  "6.2": {
    s: ["Find expectations of affine and linear combinations.", "Find variances of scaled variables and independent sums/differences.", "Combine independent normal variables.", "Combine independent Poisson variables where the result remains Poisson."],
    d: [["Linear combination", "An expression such as aX+bY+c."], ["Independence", "Knowledge of one variable gives no information about the other; required for adding variances here."], ["Covariance", "A dependence measure; it is zero for independent variables, explaining the syllabus variance rule."], ["Affine transformation", "A scaled-and-shifted variable aX+b."], ["Closure", "A distribution family stays in the same family after a stated operation."]],
    p: [["Expectation rules", "Expectation is linear whether or not variables are independent: E(aX+b)=aE(X)+b and E(aX+bY)=aE(X)+bE(Y). A constant shifts the mean directly.", ["A negative coefficient subtracts the corresponding mean.", "Independence is not needed for expectation."]], ["Variance rules", "Var(aX+b)=a²Var(X); adding a constant changes no spread. For independent X,Y, Var(aX+bY)=a²Var(X)+b²Var(Y). The variances add even for X−Y because (−1)²=1.", ["Do not subtract variances for a difference.", "Independence is essential for the syllabus formula."]], ["Normal combinations", "If X and Y are independent normal variables, aX+bY is normal with mean aμₓ+bμᵧ and variance a²σₓ²+b²σᵧ². State the complete distribution before calculating a probability.", ["Standard deviations do not add directly.", "A shift changes mean but not variance."]], ["Poisson combinations", "If independent X~Po(λ) and Y~Po(μ), then X+Y~Po(λ+μ). A difference is not Poisson. Splitting and combining counts requires independence and compatible intervals.", ["Only sums preserve the Poisson form here.", "The parameters carry the same interval units."]]],
    f: [["Affine expectation", "E(aX+b)=aE(X)+b"], ["Affine variance", "Var(aX+b)=a²Var(X)"], ["Independent combination", "Var(aX+bY)=a²Var(X)+b²Var(Y)"], ["Poisson sum", "Po(λ)+Po(μ)=Po(λ+μ), for independent variables"]],
    r: [["Does independence matter for E(X+Y)?", "No; expectation is linear regardless."], ["What is Var(X−Y) for independent X,Y?", "Var(X)+Var(Y)."], ["What does adding a constant do to variance?", "Nothing; it shifts every value equally."], ["Is X−Y Poisson when X and Y are Poisson?", "No. Only the independent sum has the stated Poisson closure property."]],
    t: ["Build the mean and variance on separate lines before standardising.", "Square every scale factor in a variance calculation."],
    m: ["Subtracting variances for X−Y.", "Adding standard deviations instead of variances.", "Using the independent-variance rule without independence."],
    rel: ["5.5", "6.1", "6.4"]
  },
  "6.3": {
    s: ["Use the defining properties of a probability density function.", "Find unknown constants by integrating total area to 1.", "Calculate probabilities and percentiles by integration.", "Find E(X), E(X²) and Var(X)."],
    d: [["Continuous random variable", "A variable able to take any real value in an interval."], ["Probability density function", "A non-negative function whose area over an interval gives probability and whose total area is 1."], ["Density", "Height per unit x; it can exceed 1 provided areas are valid probabilities."], ["Median", "A value m with equal probability on either side for a continuous distribution."], ["Support", "The interval on which the density is non-zero."]],
    p: [["Valid density functions", "A pdf f(x) must satisfy f(x)≥0 on its support and ∫f(x)dx=1 over the whole support. Use normalisation to find unknown constants, checking they keep the density non-negative.", ["A density value is not itself a point probability.", "Outside the stated support, f(x)=0."]], ["Probabilities as areas", "P(a < X < b)=∫ₐᵇf(x)dx after intersecting the requested interval with the support. For continuous X, endpoints make no difference: P(X=a)=0.", ["Draw the support and shade the required interval.", "Use complements for awkward tails."]], ["Percentiles", "A pth percentile q satisfies ∫ from the lower support limit to q of f(x)dx=p/100. The median uses 0.5. Solve and select the root that lies within the support.", ["Do not assume median equals mean unless symmetry justifies it.", "Reject algebraic roots outside the support."]], ["Moments", "Calculate E(X)=∫xf(x)dx and E(X²)=∫x²f(x)dx over the support, then Var(X)=E(X²)−[E(X)]². Interpret the mean in the same units as X and variance in squared units.", ["Normalise before calculating moments.", "Keep exact values until the variance subtraction is complete."]]],
    f: [["Normalisation", "∫ f(x) dx=1 over the support"], ["Probability", "P(a < X < b)=∫ₐᵇ f(x) dx"], ["Expectation", "E(X)=∫x f(x) dx"], ["Variance", "Var(X)=∫x²f(x) dx−[E(X)]²"]],
    r: [["Can a pdf exceed 1?", "Yes; only areas must be between 0 and 1, and total area must equal 1."], ["What is P(X=a) for continuous X?", "Zero."], ["How is the median found?", "Set the area from the lower support boundary to m equal to 0.5."], ["Which root of a percentile equation is valid?", "Only a root lying in the stated support."]],
    t: ["Write the support beside every integral.", "Check a final variance is non-negative and dimensionally sensible."],
    m: ["Treating f(a) as P(X=a).", "Integrating beyond the support without setting density to zero.", "Accepting an algebraic root outside the allowed interval."],
    rel: ["3.5", "5.4", "6.4"]
  },
  "6.4": {
    s: ["Explain why random sampling matters and identify biased procedures.", "Use the sampling distribution of the sample mean and the Central Limit Theorem.", "Calculate unbiased estimates of population mean and variance.", "Construct and interpret confidence intervals for a mean or large-sample proportion."],
    d: [["Population", "The full set about which an inference is made."], ["Sample", "A subset observed to learn about the population."], ["Sampling distribution", "The probability distribution of a statistic over repeated samples."], ["Standard error", "The standard deviation of a sampling distribution."], ["Confidence interval", "A range generated by a method that captures the true parameter at a stated long-run rate."]],
    p: [["Random samples and bias", "Every population member should have an appropriate chance of selection. Convenience, voluntary-response and incomplete-frame samples can be biased. Random numbers help choose units without personal judgement.", ["A large biased sample is still biased.", "Distinguish sampling variation from measurement error."]], ["Sample mean distribution", "If population mean is μ and variance σ², then E(X̄)=μ and Var(X̄)=σ²/n. X̄ is normal if the population is normal and approximately normal for large n by the CLT.", ["Standard error is σ/√n.", "Increasing n reduces standard error by the square-root law."]], ["Unbiased estimates", "Estimate μ by x̄. Estimate population variance with s²=Σ(x−x̄)²/(n−1), equivalently [Σx²−(Σx)²/n]/(n−1). The n−1 correction makes the estimating process unbiased.", ["Use the sample variance requested, not the descriptive variance with denominator n.", "Keep x̄ unrounded in the variance formula."]], ["Confidence intervals", "For known σ or a large sample, a confidence interval for μ is x̄±z*σ/√n, replacing σ by s for a large sample when needed. For a large-sample proportion p, use p̂±z*√[p̂(1−p̂)/n]. Interpret the confidence level as a property of the method.", ["90%, 95%, 99% use different central z-values.", "Give interval endpoints in context and sensible units."]]],
    f: [["Sample mean moments", "E(X̄)=μ; Var(X̄)=σ²/n"], ["Unbiased variance", "s²=[Σx²−(Σx)²/n]/(n−1)"], ["Mean confidence interval", "x̄±z*·σ/√n"], ["Proportion confidence interval", "p̂±z*√[p̂(1−p̂)/n]"]],
    r: [["What is the standard error of X̄?", "σ/√n."], ["Why is n−1 used in the sample variance?", "It corrects the systematic underestimation and makes the estimator unbiased."], ["What does a 95% confidence method mean?", "Across repeated samples, about 95% of intervals produced by the method contain the true parameter."], ["What happens to standard error if n is quadrupled?", "It is halved."]],
    t: ["Name the parameter and confidence level in the interpretation sentence.", "Check that a proportion interval stays sensible relative to 0 and 1."],
    m: ["Saying there is a 95% probability a fixed calculated interval contains a fixed parameter.", "Using σ/n instead of σ/√n.", "Using denominator n for the required unbiased sample-variance estimate."],
    rel: ["5.1", "5.5", "6.5"]
  },
  "6.5": {
    s: ["State H₀ and H₁ and choose one- or two-tailed tests.", "Use exact binomial/Poisson probabilities or suitable normal approximations.", "Test a population mean with known variance or a large sample.", "Calculate and interpret Type I and Type II error probabilities."],
    d: [["Null hypothesis", "H₀, the model or parameter value tested as the default claim."], ["Alternative hypothesis", "H₁, the direction or difference supported if H₀ is rejected."], ["Significance level", "The maximum chosen probability of rejecting H₀ when it is true."], ["Critical region", "Test-statistic values that lead to rejection of H₀."], ["p-value", "The probability under H₀ of an outcome at least as extreme as observed in the direction(s) of H₁."], ["Type I error", "Rejecting a true H₀."], ["Type II error", "Failing to reject a false H₀ under a specified alternative."]],
    p: [["Setting up the test", "Define the parameter, write H₀ with equality, and make H₁ match the claim. 'Increased' gives an upper tail, 'decreased' a lower tail, and 'changed' two tails. The test calculation always uses the H₀ parameter.", ["Use population parameters, not sample statistics, in hypotheses.", "Choose the tail before seeing the result."]], ["Discrete tests", "For X binomial or Poisson, find the probability of the observed result or something more extreme under H₀. Reject if that p-value is ≤α. A critical region is chosen so its H₀ probability is at most α; discreteness means the actual size may be smaller.", ["For two tails, identify both extremes rather than blindly doubling if the distribution is asymmetric.", "State the actual critical-region probability when requested."]], ["Normal and mean tests", "Use a continuity-corrected normal approximation for binomial/Poisson when conditions hold. For a mean, standardise Z=(X̄−μ₀)/(σ/√n), using s for σ in a large-sample setting as allowed, then compare with the relevant critical value or p-value.", ["Put μ₀ from H₀ in the numerator.", "A two-tailed α test places α/2 in each tail."]], ["Errors and conclusions", "Type I probability is the rejection-region probability under H₀. Type II probability is the acceptance-region probability under a specified alternative. Finish with 'reject H₀' or 'do not reject H₀', followed by a contextual evidence statement—never say H₀ is proved.", ["Power=1−P(Type II error).", "The conclusion must use the direction in H₁."]]],
    f: [["Mean test statistic", "Z=(X̄−μ₀)/(σ/√n)"], ["Decision by p-value", "reject H₀ when p≤α"], ["Type I error", "P(rejection region | H₀ true)"], ["Type II error", "P(acceptance region | specified H₁ true)"]],
    r: [["Where does equality belong in hypotheses?", "In H₀."], ["What tail matches 'the mean has decreased'?", "A lower-tailed test."], ["What is a Type I error?", "Rejecting H₀ when H₀ is true."], ["How should a non-significant result be stated?", "Do not reject H₀; there is insufficient evidence for the contextual alternative claim."]],
    t: ["Write hypotheses and significance level before calculating probabilities.", "End with a decision and a separate sentence in the language of the question."],
    m: ["Saying 'accept H₀' or 'prove H₀'.", "Using the observed sample proportion instead of the H₀ probability in a binomial test.", "Forgetting α/2 in each tail of a two-tailed normal test."],
    rel: ["5.5", "6.1", "6.4"]
  }
};
