param(
  [string]$LibraryRoot = (Join-Path $PSScriptRoot '..\..\..\CAIE_Library_Downloader_v3_XtraPapers\CAIE_Library_Downloader_v3_XtraPapers\library'),
  [string]$OutputPath = (Join-Path $PSScriptRoot '..\data\papers.js')
)

$ErrorActionPreference = 'Stop'
$libraryPath = (Resolve-Path -LiteralPath $LibraryRoot).Path
$outputFile = [System.IO.Path]::GetFullPath($OutputPath)
$manifestPath = Join-Path $libraryPath 'papers.json'

$subjectByCode = @{
  '9609' = @{ title = 'Business'; slug = 'business-9609' }
  '9618' = @{ title = 'Computer Science'; slug = 'computer-science-9618' }
  '9701' = @{ title = 'Chemistry'; slug = 'chemistry-9701' }
  '9709' = @{ title = 'Mathematics'; slug = 'mathematics-9709' }
}
$sessionByCode = @{
  'm' = @{ title = 'February–March'; slug = 'march'; order = 1 }
  's' = @{ title = 'May–June'; slug = 'may-june'; order = 2 }
  'w' = @{ title = 'October–November'; slug = 'october-november'; order = 3 }
}

$sourceByFilename = @{}
if(Test-Path -LiteralPath $manifestPath){
  foreach($item in (Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json)){
    if($item.filename -and $item.source){
      $sourceByFilename[$item.filename] = $item.source
    }
  }
}

$records = foreach($file in (Get-ChildItem -LiteralPath $libraryPath -Recurse -File -Filter '*.pdf')){
  if($file.Name -notmatch '^(?<code>\d{4})_(?<session>[msw])(?<year>\d{2})_(?<type>qp|ms)_(?<paper>\d{2})\.pdf$'){
    Write-Warning "Skipping unrecognised PDF name: $($file.Name)"
    continue
  }

  $code = $Matches.code
  if(-not $subjectByCode.ContainsKey($code)){ continue }
  $year = 2000 + [int]$Matches.year
  $sessionCode = $Matches.session
  $session = $sessionByCode[$sessionCode]
  $subject = $subjectByCode[$code]
  $source = $sourceByFilename[$file.Name]
  if(-not $source){
    $source = "https://xtrapapers.co/papers/caie/as-and-a-level/$($subject.slug)/$year-$($session.slug)/$($file.Name)/download"
  }

  [pscustomobject]@{
    code = $code
    subject = $subject.title
    year = $year
    sessionCode = $sessionCode
    session = $session.title
    sessionOrder = $session.order
    paper = $Matches.paper
    type = $Matches.type
    source = $source
  }
}

$pairs = foreach($group in ($records | Group-Object { "$($_.code)|$($_.year)|$($_.sessionCode)|$($_.paper)" })){
  $questionPaper = $group.Group | Where-Object type -eq 'qp' | Select-Object -First 1
  $markScheme = $group.Group | Where-Object type -eq 'ms' | Select-Object -First 1
  if(-not $questionPaper -or -not $markScheme){
    Write-Warning "Skipping incomplete pair: $($group.Name)"
    continue
  }

  [pscustomobject][ordered]@{
    code = $questionPaper.code
    subject = $questionPaper.subject
    year = $questionPaper.year
    session = $questionPaper.session
    sessionCode = $questionPaper.sessionCode
    paper = $questionPaper.paper
    questionPaper = $questionPaper.source
    markScheme = $markScheme.source
    sessionOrder = $questionPaper.sessionOrder
  }
}

$sortProperties = @(
  @{ Expression = 'year'; Descending = $true }
  @{ Expression = 'sessionOrder'; Descending = $true }
  @{ Expression = 'code'; Descending = $false }
  @{ Expression = { [int]$_.paper }; Descending = $false }
)
$sortedPairs = $pairs | Sort-Object -Property $sortProperties

$publicPairs = $sortedPairs | Select-Object code,subject,year,session,sessionCode,paper,questionPaper,markScheme
$json = $publicPairs | ConvertTo-Json -Depth 4
$header = @"
/* Generated by scripts/generate-papers-data.ps1 from the local downloader library.
   Do not edit by hand; refresh the library and rerun the generator instead. */
const PAST_PAPERS = $json;
"@

[System.IO.File]::WriteAllText($outputFile, $header, [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $($publicPairs.Count) complete paper pairs at $outputFile"
